//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impac.Mosaiq.IQ.Activities.DICOM {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Impac.Mosaiq.IQ.Activities.DICOM.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The return result from the Activity.
        /// </summary>
        internal static string ActivityStatus_Description {
            get {
                return ResourceManager.GetString("ActivityStatus_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Status.
        /// </summary>
        internal static string ActivityStatus_DisplayName {
            get {
                return ResourceManager.GetString("ActivityStatus_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check iViewGT Auto-Isocenter Exclusions.
        /// </summary>
        internal static string CheckIViewGTAutoIsocExclusionsActivity_DisplayName {
            get {
                return ResourceManager.GetString("CheckIViewGTAutoIsocExclusionsActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert Existing Volumes for Image Series Activity.
        /// </summary>
        internal static string ConvertExistingVolumesActivity_DisplayName {
            get {
                return ResourceManager.GetString("ConvertExistingVolumesActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create the Anatomy Sets for the RTSS.
        /// </summary>
        internal static string CreateAnatomySetsActivity_DisplayName {
            get {
                return ResourceManager.GetString("CreateAnatomySetsActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Avs For Image Series Activity.
        /// </summary>
        internal static string CreateAvsForImageSeriesActivity_DisplayName {
            get {
                return ResourceManager.GetString("CreateAvsForImageSeriesActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Dose Matrix Entry .
        /// </summary>
        internal static string CreateDoseMatrixEntry_DisplayName {
            get {
                return ResourceManager.GetString("CreateDoseMatrixEntry_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Frame Of Reference Relationship Record.
        /// </summary>
        internal static string CreateFrameOfReferenceRelationshipRecord_DisplayName {
            get {
                return ResourceManager.GetString("CreateFrameOfReferenceRelationshipRecord_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Offset Record.
        /// </summary>
        internal static string CreateOffsetRecord_DisplayName {
            get {
                return ResourceManager.GetString("CreateOffsetRecord_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Registration Record.
        /// </summary>
        internal static string CreateRegistrationRecord_DisplayName {
            get {
                return ResourceManager.GetString("CreateRegistrationRecord_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Related Series Link Record Activity.
        /// </summary>
        internal static string CreateRelatedSeriesLinkRecordActivity_DisplayName {
            get {
                return ResourceManager.GetString("CreateRelatedSeriesLinkRecordActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ID of the DcmInstance in the DcmInstance Table.
        /// </summary>
        internal static string DcmInstanceID_Description {
            get {
                return ResourceManager.GetString("DcmInstanceID_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DcmInstanceID.
        /// </summary>
        internal static string DcmInstanceID_DisplayName {
            get {
                return ResourceManager.GetString("DcmInstanceID_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DICOM.
        /// </summary>
        internal static string DICOM_ActivityGroup {
            get {
                return ResourceManager.GetString("DICOM_ActivityGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Spatial Registration Data Navigator.
        /// </summary>
        internal static string DisplaySpatialRegistrationDataNavigator_DisplayName {
            get {
                return ResourceManager.GetString("DisplaySpatialRegistrationDataNavigator_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract the Spatial Isocenter Coordinates from an RT Structure Set.
        /// </summary>
        internal static string ExtractStructureSetSpatialIsocenterCoordinates_DisplayName {
            get {
                return ResourceManager.GetString("ExtractStructureSetSpatialIsocenterCoordinates_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate the Surface Mesh for the RTSS.
        /// </summary>
        internal static string GenerateSurfaceMeshActivity_DisplayName {
            get {
                return ResourceManager.GetString("GenerateSurfaceMeshActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Referencec Plan Instances For a, RTDose.
        /// </summary>
        internal static string GetReferencePlanInstancesForADose_DisplayName {
            get {
                return ResourceManager.GetString("GetReferencePlanInstancesForADose_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identify Spatial Registration Object.
        /// </summary>
        internal static string IdentifySpatialRegistrationObject_DisplayName {
            get {
                return ResourceManager.GetString("IdentifySpatialRegistrationObject_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Series .
        /// </summary>
        internal static string ImageSeries_Category {
            get {
                return ResourceManager.GetString("ImageSeries_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert RT Image Position value into an RT-Image from iViewGT.
        /// </summary>
        internal static string InsertIViewGTRTImagePositionActivity_DisplayName {
            get {
                return ResourceManager.GetString("InsertIViewGTRTImagePositionActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Object a Simple and Generic Spatial Registration.
        /// </summary>
        internal static string IsObjectSimpleAndGenericSpatialRegistration_DisplayName {
            get {
                return ResourceManager.GetString("IsObjectSimpleAndGenericSpatialRegistration_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Object Treatment Delivery Based.
        /// </summary>
        internal static string IsObjectTreatmentDeliveryBased_DisplayName {
            get {
                return ResourceManager.GetString("IsObjectTreatmentDeliveryBased_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Object an XVI 5.x Spatial Registration.
        /// </summary>
        internal static string IsObjectXVI5xSpatialRegistrationObject_DisplayName {
            get {
                return ResourceManager.GetString("IsObjectXVI5xSpatialRegistrationObject_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DICOM RTImage file pathname of a portal image from iViewGT.
        /// </summary>
        internal static string IViewGTPortalImageFilename_Description {
            get {
                return ResourceManager.GetString("IViewGTPortalImageFilename_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IViewGTPortalImageFilename.
        /// </summary>
        internal static string IViewGTPortalImageFilename_DisplayName {
            get {
                return ResourceManager.GetString("IViewGTPortalImageFilename_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RTImage from iViewGT.
        /// </summary>
        internal static string IViewGTRTImage_Category {
            get {
                return ResourceManager.GetString("IViewGTRTImage_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compute RT Image Position value for an RT-Image from iViewGT.
        /// </summary>
        internal static string LocateIViewGTRTImagePositionActivity_DisplayName {
            get {
                return ResourceManager.GetString("LocateIViewGTRTImagePositionActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move iViewGT RT Image file to Staging Area.
        /// </summary>
        internal static string MoveIViewGTRTImageFileToStagingAreaActivity_DisplayName {
            get {
                return ResourceManager.GetString("MoveIViewGTRTImageFileToStagingAreaActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RT Plan unit id associated with this dose..
        /// </summary>
        internal static string OutPlanUnitId_Description {
            get {
                return ResourceManager.GetString("OutPlanUnitId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RTPlanUnitId.
        /// </summary>
        internal static string OutPlanUnitId_DisplayName {
            get {
                return ResourceManager.GetString("OutPlanUnitId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RPS UnitId Pass through, Allows to convey to the following activity..
        /// </summary>
        internal static string OutRPSUnitId_Description {
            get {
                return ResourceManager.GetString("OutRPSUnitId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RPS UnitId.
        /// </summary>
        internal static string OutRPSUnitId_DisplayName {
            get {
                return ResourceManager.GetString("OutRPSUnitId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structure Set UnitIds to convey to following Activities..
        /// </summary>
        internal static string OutStructureSetIds_Description {
            get {
                return ResourceManager.GetString("OutStructureSetIds_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OutStructureSetIds.
        /// </summary>
        internal static string OutStructureSetIds_DisplayName {
            get {
                return ResourceManager.GetString("OutStructureSetIds_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnitId Pass through, Allows to convey to the following activity..
        /// </summary>
        internal static string OutUnitId_Description {
            get {
                return ResourceManager.GetString("OutUnitId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OutUnitId.
        /// </summary>
        internal static string OutUnitId_DisplayName {
            get {
                return ResourceManager.GetString("OutUnitId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parse Treatment Delivery Based Spatial Registration Object.
        /// </summary>
        internal static string ParseTreatmentDeliverySpatialRegistrationObject_DisplayName {
            get {
                return ResourceManager.GetString("ParseTreatmentDeliverySpatialRegistrationObject_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parse Treatment Planning Based Spatial Registration Object.
        /// </summary>
        internal static string ParseTreatmentPlanningSpatialRegistrationObject_DisplayName {
            get {
                return ResourceManager.GetString("ParseTreatmentPlanningSpatialRegistrationObject_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parse XVI 5.x Spatial Registration Object.
        /// </summary>
        internal static string ParseXVI5xSpatialRegistrationObject_DisplayName {
            get {
                return ResourceManager.GetString("ParseXVI5xSpatialRegistrationObject_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Populate LGK Registry Holding Table with Gamma Plan Information.
        /// </summary>
        internal static string PopulateLGKRegistryHoldingTableActivity_DisplayName {
            get {
                return ResourceManager.GetString("PopulateLGKRegistryHoldingTableActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Conventional RTPlan Activity.
        /// </summary>
        internal static string PopulatePlanAndBeamTablesActivity_DisplayName {
            get {
                return ResourceManager.GetString("PopulatePlanAndBeamTablesActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Populate VRS records from XVI RPS.
        /// </summary>
        internal static string PopulateRPSTablesActivity_DisplayName {
            get {
                return ResourceManager.GetString("PopulateRPSTablesActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Regeneration Request for related prior DCMseries..
        /// </summary>
        internal static string PostRegenerateAvsForImageSeriesActivity_DisplayName {
            get {
                return ResourceManager.GetString("PostRegenerateAvsForImageSeriesActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create the Dose Volume.
        /// </summary>
        internal static string ProcessDoseCreateDoseVolume_DisplayName {
            get {
                return ResourceManager.GetString("ProcessDoseCreateDoseVolume_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Generic Spatial Registration.
        /// </summary>
        internal static string ProcessGenericSpatialRegistration_DisplayName {
            get {
                return ResourceManager.GetString("ProcessGenericSpatialRegistration_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process XVI 5.x Spatial Registration.
        /// </summary>
        internal static string ProcessXVI5xSpatialRegistration_DisplayName {
            get {
                return ResourceManager.GetString("ProcessXVI5xSpatialRegistration_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purge AVS.
        /// </summary>
        internal static string PurgeAVS_Category {
            get {
                return ResourceManager.GetString("PurgeAVS_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purge Avs For Image Series Activity.
        /// </summary>
        internal static string PurgeAvsForImageSeriesActivity_DisplayName {
            get {
                return ResourceManager.GetString("PurgeAvsForImageSeriesActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An array of referenced plan instances for an RTDose.
        /// </summary>
        internal static string ReferencedPlanSOPInstances_Description {
            get {
                return ResourceManager.GetString("ReferencedPlanSOPInstances_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referenced Plan SOP Instances.
        /// </summary>
        internal static string ReferencedPlanSOPInstances_DisplayName {
            get {
                return ResourceManager.GetString("ReferencedPlanSOPInstances_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regenerate Avs For Image Series Activity.
        /// </summary>
        internal static string RegenerateAvsForImageSeriesActivity_DisplayName {
            get {
                return ResourceManager.GetString("RegenerateAvsForImageSeriesActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RPS XVI Reference Parameter Set.
        /// </summary>
        internal static string RPS_Category {
            get {
                return ResourceManager.GetString("RPS_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOP Instance UID of the RPS object.
        /// </summary>
        internal static string RPSUid_Description {
            get {
                return ResourceManager.GetString("RPSUid_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RPSUid.
        /// </summary>
        internal static string RPSUid_DisplayName {
            get {
                return ResourceManager.GetString("RPSUid_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCMInstance ID of the RPS.
        /// </summary>
        internal static string RpsUnitId_Description {
            get {
                return ResourceManager.GetString("RpsUnitId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RPS UnitId.
        /// </summary>
        internal static string RpsUnitId_DisplayName {
            get {
                return ResourceManager.GetString("RpsUnitId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RtDose.
        /// </summary>
        internal static string RTDose_Category {
            get {
                return ResourceManager.GetString("RTDose_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X Coordinate, in millimeters, for DICOM RT Image Position (3002, 0012) attribute.
        /// </summary>
        internal static string RtImagePositionXmm_Description {
            get {
                return ResourceManager.GetString("RtImagePositionXmm_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RTImagePositionX.
        /// </summary>
        internal static string RtImagePositionXmm_DisplayName {
            get {
                return ResourceManager.GetString("RtImagePositionXmm_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y Coordinate, in millimeters, for DICOM RT Image Position (3002, 0012) attribute.
        /// </summary>
        internal static string RtImagePositionYmm_Description {
            get {
                return ResourceManager.GetString("RtImagePositionYmm_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RTImagePositionY.
        /// </summary>
        internal static string RtImagePositionYmm_DisplayName {
            get {
                return ResourceManager.GetString("RtImagePositionYmm_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RTPlan.
        /// </summary>
        internal static string RTPlan_Category {
            get {
                return ResourceManager.GetString("RTPlan_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RT StructureSet.
        /// </summary>
        internal static string RTStructureSet_Category {
            get {
                return ResourceManager.GetString("RTStructureSet_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the Spatial Isocenter Coordinates from an RT Structure Set.
        /// </summary>
        internal static string SaveStructureSetSpatialIsocenterCoordinates_DisplayName {
            get {
                return ResourceManager.GetString("SaveStructureSetSpatialIsocenterCoordinates_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send SRO Processed Message.
        /// </summary>
        internal static string SendSroProcessedMessage_DisplayName {
            get {
                return ResourceManager.GetString("SendSroProcessedMessage_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site SET ID of the Site.
        /// </summary>
        internal static string SiteID_Description {
            get {
                return ResourceManager.GetString("SiteID_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SiteID.
        /// </summary>
        internal static string SiteID_DisplayName {
            get {
                return ResourceManager.GetString("SiteID_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spatial Registration.
        /// </summary>
        internal static string SpatialRegistration_Category {
            get {
                return ResourceManager.GetString("SpatialRegistration_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCMInstance ID of the SRO.
        /// </summary>
        internal static string SroUnitId_Description {
            get {
                return ResourceManager.GetString("SroUnitId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SRO UnitId.
        /// </summary>
        internal static string SroUnitId_DisplayName {
            get {
                return ResourceManager.GetString("SroUnitId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID of the Object to be acted on..
        /// </summary>
        internal static string UnitId_Description {
            get {
                return ResourceManager.GetString("UnitId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnitId.
        /// </summary>
        internal static string UnitId_DisplayName {
            get {
                return ResourceManager.GetString("UnitId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DICOM RT Image file with updated RT Image Position.
        /// </summary>
        internal static string UpdatedFilename_Description {
            get {
                return ResourceManager.GetString("UpdatedFilename_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdatedFilename.
        /// </summary>
        internal static string UpdatedFilename_DisplayName {
            get {
                return ResourceManager.GetString("UpdatedFilename_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Frame Of Reference Relationship Record.
        /// </summary>
        internal static string UpdateFrameOfReferenceRelationshipRecord_DisplayName {
            get {
                return ResourceManager.GetString("UpdateFrameOfReferenceRelationshipRecord_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Offset Record.
        /// </summary>
        internal static string UpdateOffsetRecord_DisplayName {
            get {
                return ResourceManager.GetString("UpdateOffsetRecord_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Registration Record.
        /// </summary>
        internal static string UpdateRegistrationRecord_DisplayName {
            get {
                return ResourceManager.GetString("UpdateRegistrationRecord_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for Dose Referenced Plan Data.
        /// </summary>
        internal static string WaitForDoseObjectPlanActivity_DisplayName {
            get {
                return ResourceManager.GetString("WaitForDoseObjectPlanActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for Dose Volume Dependent Structure Set .
        /// </summary>
        internal static string WaitForDoseObjectStructureSetDataActivity_DisplayName {
            get {
                return ResourceManager.GetString("WaitForDoseObjectStructureSetDataActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for Spatial Registration Dependent Images.
        /// </summary>
        internal static string WaitForSpatialRegistrationImageDataActivity_DisplayName {
            get {
                return ResourceManager.GetString("WaitForSpatialRegistrationImageDataActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for Spatial Registration RPS Data.
        /// </summary>
        internal static string WaitForSpatialRegistrationRPSDataActivity_DisplayName {
            get {
                return ResourceManager.GetString("WaitForSpatialRegistrationRPSDataActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for Spatial Registration Dependent Structure Set.
        /// </summary>
        internal static string WaitForSpatialRegistrationStructureSetDataActivity_DisplayName {
            get {
                return ResourceManager.GetString("WaitForSpatialRegistrationStructureSetDataActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for Structure Set Referenced data.
        /// </summary>
        internal static string WaitForStructureSetObjectActivity_DisplayName {
            get {
                return ResourceManager.GetString("WaitForStructureSetObjectActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait For Volume AVS file to be created..
        /// </summary>
        internal static string WaitForVolumeAVSFileToBeAvailableActivity_DisplayName {
            get {
                return ResourceManager.GetString("WaitForVolumeAVSFileToBeAvailableActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for Dependent Images for XVI 5x Spatial Registration .
        /// </summary>
        internal static string WaitForXVI5xSpatialRegistrationImageDataActivity_DisplayName {
            get {
                return ResourceManager.GetString("WaitForXVI5xSpatialRegistrationImageDataActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Id of the Work Queue Element in the WorkQueueElement table..
        /// </summary>
        internal static string WorkQueueElementID_Description {
            get {
                return ResourceManager.GetString("WorkQueueElementID_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Queue Element ID..
        /// </summary>
        internal static string WorkQueueElementID_DisplayName {
            get {
                return ResourceManager.GetString("WorkQueueElementID_DisplayName", resourceCulture);
            }
        }
    }
}
