//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impac.Mosaiq.IQ.Activities.General {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Impac.Mosaiq.IQ.Activities.General.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string Boolean_False {
            get {
                return ResourceManager.GetString("Boolean_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Boolean_True {
            get {
                return ResourceManager.GetString("Boolean_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Care Plans.
        /// </summary>
        internal static string Careplan_Category {
            get {
                return ResourceManager.GetString("Careplan_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Item Thresholds.
        /// </summary>
        internal static string CheckDataItemThresholdsActivity_DataItemThresholds_Description {
            get {
                return ResourceManager.GetString("CheckDataItemThresholdsActivity_DataItemThresholds_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Item Thresholds.
        /// </summary>
        internal static string CheckDataItemThresholdsActivity_DataItemThresholds_DisplayName {
            get {
                return ResourceManager.GetString("CheckDataItemThresholdsActivity_DataItemThresholds_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Data Item Thresholds.
        /// </summary>
        internal static string CheckDataItemThresholdsActivity_DisplayName {
            get {
                return ResourceManager.GetString("CheckDataItemThresholdsActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OBR ID.
        /// </summary>
        internal static string CheckDataItemThresholdsActivity_ObrId_Description {
            get {
                return ResourceManager.GetString("CheckDataItemThresholdsActivity_ObrId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OBR ID.
        /// </summary>
        internal static string CheckDataItemThresholdsActivity_ObrId_DisplayName {
            get {
                return ResourceManager.GetString("CheckDataItemThresholdsActivity_ObrId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string CheckDataItemThresholdsActivity_Success_Description {
            get {
                return ResourceManager.GetString("CheckDataItemThresholdsActivity_Success_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string CheckDataItemThresholdsActivity_Success_DisplayName {
            get {
                return ResourceManager.GetString("CheckDataItemThresholdsActivity_Success_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string CreateDocumentActivity_Account_Description {
            get {
                return ResourceManager.GetString("CreateDocumentActivity_Account_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string CreateDocumentActivity_Account_DisplayName {
            get {
                return ResourceManager.GetString("CreateDocumentActivity_Account_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Co-Sign Required By.
        /// </summary>
        internal static string CreateDocumentActivity_CosignRequiredBy_Description {
            get {
                return ResourceManager.GetString("CreateDocumentActivity_CosignRequiredBy_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Co-Sign Required By.
        /// </summary>
        internal static string CreateDocumentActivity_CosignRequiredBy_DisplayName {
            get {
                return ResourceManager.GetString("CreateDocumentActivity_CosignRequiredBy_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create If Duplicate Exists.
        /// </summary>
        internal static string CreateDocumentActivity_CreateIfDuplicateExists_Description {
            get {
                return ResourceManager.GetString("CreateDocumentActivity_CreateIfDuplicateExists_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create If Duplicate Exists.
        /// </summary>
        internal static string CreateDocumentActivity_CreateIfDuplicateExists_DisplayName {
            get {
                return ResourceManager.GetString("CreateDocumentActivity_CreateIfDuplicateExists_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departement.
        /// </summary>
        internal static string CreateDocumentActivity_Department_Description {
            get {
                return ResourceManager.GetString("CreateDocumentActivity_Department_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string CreateDocumentActivity_Department_DisplayName {
            get {
                return ResourceManager.GetString("CreateDocumentActivity_Department_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a new eScribe document using the specified template and other parameters.
        /// </summary>
        internal static string CreateDocumentActivity_Description {
            get {
                return ResourceManager.GetString("CreateDocumentActivity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictated By.
        /// </summary>
        internal static string CreateDocumentActivity_DictatedBy_Description {
            get {
                return ResourceManager.GetString("CreateDocumentActivity_DictatedBy_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictated By.
        /// </summary>
        internal static string CreateDocumentActivity_DictatedBy_DisplayName {
            get {
                return ResourceManager.GetString("CreateDocumentActivity_DictatedBy_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Document.
        /// </summary>
        internal static string CreateDocumentActivity_DisplayName {
            get {
                return ResourceManager.GetString("CreateDocumentActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Type.
        /// </summary>
        internal static string CreateDocumentActivity_DocType_Description {
            get {
                return ResourceManager.GetString("CreateDocumentActivity_DocType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Type.
        /// </summary>
        internal static string CreateDocumentActivity_DocType_DisplayName {
            get {
                return ResourceManager.GetString("CreateDocumentActivity_DocType_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encounter Date.
        /// </summary>
        internal static string CreateDocumentActivity_EncounterDate_Description {
            get {
                return ResourceManager.GetString("CreateDocumentActivity_EncounterDate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encounter Date.
        /// </summary>
        internal static string CreateDocumentActivity_EncounterDate_DisplayName {
            get {
                return ResourceManager.GetString("CreateDocumentActivity_EncounterDate_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open After Creation.
        /// </summary>
        internal static string CreateDocumentActivity_OpenAfterCreation_Description {
            get {
                return ResourceManager.GetString("CreateDocumentActivity_OpenAfterCreation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open After Creation.
        /// </summary>
        internal static string CreateDocumentActivity_OpenAfterCreation_DisplayName {
            get {
                return ResourceManager.GetString("CreateDocumentActivity_OpenAfterCreation_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pat ID1.
        /// </summary>
        internal static string CreateDocumentActivity_PatId1_Description {
            get {
                return ResourceManager.GetString("CreateDocumentActivity_PatId1_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pat ID1.
        /// </summary>
        internal static string CreateDocumentActivity_PatId1_DisplayName {
            get {
                return ResourceManager.GetString("CreateDocumentActivity_PatId1_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Required By.
        /// </summary>
        internal static string CreateDocumentActivity_ReviewRequiredBy_Description {
            get {
                return ResourceManager.GetString("CreateDocumentActivity_ReviewRequiredBy_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Required By.
        /// </summary>
        internal static string CreateDocumentActivity_ReviewRequiredBy_DisplayName {
            get {
                return ResourceManager.GetString("CreateDocumentActivity_ReviewRequiredBy_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string CreateDocumentActivity_Status_Description {
            get {
                return ResourceManager.GetString("CreateDocumentActivity_Status_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string CreateDocumentActivity_Status_DisplayName {
            get {
                return ResourceManager.GetString("CreateDocumentActivity_Status_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eScribe template to use.
        /// </summary>
        internal static string CreateDocumentActivity_Template_Description {
            get {
                return ResourceManager.GetString("CreateDocumentActivity_Template_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        internal static string CreateDocumentActivity_Template_DisplayName {
            get {
                return ResourceManager.GetString("CreateDocumentActivity_Template_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transcribed By.
        /// </summary>
        internal static string CreateDocumentActivity_TranscribedBy_Description {
            get {
                return ResourceManager.GetString("CreateDocumentActivity_TranscribedBy_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transcribed By.
        /// </summary>
        internal static string CreateDocumentActivity_TranscribedBy_DisplayName {
            get {
                return ResourceManager.GetString("CreateDocumentActivity_TranscribedBy_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transcribed Date.
        /// </summary>
        internal static string CreateDocumentActivity_TranscribedDate_Description {
            get {
                return ResourceManager.GetString("CreateDocumentActivity_TranscribedDate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transcribed Date.
        /// </summary>
        internal static string CreateDocumentActivity_TranscribedDate_DisplayName {
            get {
                return ResourceManager.GetString("CreateDocumentActivity_TranscribedDate_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternate Separators.
        /// </summary>
        internal static string CurrentDateActivity_AlternateSeparators_Description {
            get {
                return ResourceManager.GetString("CurrentDateActivity_AlternateSeparators_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternate Separators.
        /// </summary>
        internal static string CurrentDateActivity_AlternateSeparators_DisplayName {
            get {
                return ResourceManager.GetString("CurrentDateActivity_AlternateSeparators_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blank if No Date.
        /// </summary>
        internal static string CurrentDateActivity_BlankIfNoDate_Description {
            get {
                return ResourceManager.GetString("CurrentDateActivity_BlankIfNoDate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blank if No Date.
        /// </summary>
        internal static string CurrentDateActivity_BlankIfNoDate_DisplayName {
            get {
                return ResourceManager.GetString("CurrentDateActivity_BlankIfNoDate_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capitalization.
        /// </summary>
        internal static string CurrentDateActivity_Capitalization_Description {
            get {
                return ResourceManager.GetString("CurrentDateActivity_Capitalization_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capitalization.
        /// </summary>
        internal static string CurrentDateActivity_Capitalization_DisplayName {
            get {
                return ResourceManager.GetString("CurrentDateActivity_Capitalization_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Format.
        /// </summary>
        internal static string CurrentDateActivity_DateFormat_Description {
            get {
                return ResourceManager.GetString("CurrentDateActivity_DateFormat_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Format.
        /// </summary>
        internal static string CurrentDateActivity_DateFormat_DisplayName {
            get {
                return ResourceManager.GetString("CurrentDateActivity_DateFormat_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Date.
        /// </summary>
        internal static string CurrentDateActivity_DisplayName {
            get {
                return ResourceManager.GetString("CurrentDateActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Html.
        /// </summary>
        internal static string CurrentDateActivity_Html_Description {
            get {
                return ResourceManager.GetString("CurrentDateActivity_Html_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Html.
        /// </summary>
        internal static string CurrentDateActivity_Html_DisplayName {
            get {
                return ResourceManager.GetString("CurrentDateActivity_Html_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Leading Spaces.
        /// </summary>
        internal static string CurrentDateActivity_KeepLeadingSpaces_Description {
            get {
                return ResourceManager.GetString("CurrentDateActivity_KeepLeadingSpaces_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Leading Spaces.
        /// </summary>
        internal static string CurrentDateActivity_KeepLeadingSpaces_DisplayName {
            get {
                return ResourceManager.GetString("CurrentDateActivity_KeepLeadingSpaces_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plain Text.
        /// </summary>
        internal static string CurrentDateActivity_PlainText_Description {
            get {
                return ResourceManager.GetString("CurrentDateActivity_PlainText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plain Text.
        /// </summary>
        internal static string CurrentDateActivity_PlainText_DisplayName {
            get {
                return ResourceManager.GetString("CurrentDateActivity_PlainText_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepend Day of Week.
        /// </summary>
        internal static string CurrentDateActivity_PrependDayOfWeek_Description {
            get {
                return ResourceManager.GetString("CurrentDateActivity_PrependDayOfWeek_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepend Day of Week.
        /// </summary>
        internal static string CurrentDateActivity_PrependDayOfWeek_DisplayName {
            get {
                return ResourceManager.GetString("CurrentDateActivity_PrependDayOfWeek_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} observation definition data format not supported.
        /// </summary>
        internal static string Error_InvalidObsDefDataFormat {
            get {
                return ResourceManager.GetString("Error_InvalidObsDefDataFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eSCRIBE.
        /// </summary>
        internal static string Escribe_Category {
            get {
                return ResourceManager.GetString("Escribe_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flowsheet.
        /// </summary>
        internal static string Flowsheet_Category {
            get {
                return ResourceManager.GetString("Flowsheet_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The return result of the assessment form..
        /// </summary>
        internal static string FlowsheetFormActivity_DialogResult_Description {
            get {
                return ResourceManager.GetString("FlowsheetFormActivity_DialogResult_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog Result.
        /// </summary>
        internal static string FlowsheetFormActivity_DialogResult_DisplayName {
            get {
                return ResourceManager.GetString("FlowsheetFormActivity_DialogResult_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flowsheet Form.
        /// </summary>
        internal static string FlowsheetFormActivity_DisplayName {
            get {
                return ResourceManager.GetString("FlowsheetFormActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets whether the assessment will be marked as reviewed..
        /// </summary>
        internal static string FlowsheetFormActivity_MarkReviewed_Description {
            get {
                return ResourceManager.GetString("FlowsheetFormActivity_MarkReviewed_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark Reviewed.
        /// </summary>
        internal static string FlowsheetFormActivity_MarkReviewed_DisplayName {
            get {
                return ResourceManager.GetString("FlowsheetFormActivity_MarkReviewed_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates whether the activity should populate the form is modal or not. This field is optional. Default value is false..
        /// </summary>
        internal static string FlowsheetFormActivity_ModalDialog_Description {
            get {
                return ResourceManager.GetString("FlowsheetFormActivity_ModalDialog_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modal Dialog.
        /// </summary>
        internal static string FlowsheetFormActivity_ModalDialog_DisplayName {
            get {
                return ResourceManager.GetString("FlowsheetFormActivity_ModalDialog_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The flowsheet tab view which will be displayed in the form..
        /// </summary>
        internal static string FlowsheetFormActivity_ObdGuid_Description {
            get {
                return ResourceManager.GetString("FlowsheetFormActivity_ObdGuid_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab View.
        /// </summary>
        internal static string FlowsheetFormActivity_ObdGuid_DisplayName {
            get {
                return ResourceManager.GetString("FlowsheetFormActivity_ObdGuid_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Obr_Id of the ObsReq record created by the form..
        /// </summary>
        internal static string FlowsheetFormActivity_ObrId_Description {
            get {
                return ResourceManager.GetString("FlowsheetFormActivity_ObrId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obr_Id.
        /// </summary>
        internal static string FlowsheetFormActivity_ObrId_DisplayName {
            get {
                return ResourceManager.GetString("FlowsheetFormActivity_ObrId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient IDfor the Observe Record.
        /// </summary>
        internal static string FlowsheetFormActivity_PatientId_Description {
            get {
                return ResourceManager.GetString("FlowsheetFormActivity_PatientId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient ID.
        /// </summary>
        internal static string FlowsheetFormActivity_PatientId_DisplayName {
            get {
                return ResourceManager.GetString("FlowsheetFormActivity_PatientId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates whether the activity should return a result, i.e. display the UDD form synchronously.
        /// </summary>
        internal static string FlowsheetFormActivity_ReturnResult_Description {
            get {
                return ResourceManager.GetString("FlowsheetFormActivity_ReturnResult_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Result.
        /// </summary>
        internal static string FlowsheetFormActivity_ReturnResult_DisplayName {
            get {
                return ResourceManager.GetString("FlowsheetFormActivity_ReturnResult_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab view not found.
        /// </summary>
        internal static string FlowsheetFormActivity_TabViewNotFound {
            get {
                return ResourceManager.GetString("FlowsheetFormActivity_TabViewNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IQScriptUddForm.
        /// </summary>
        internal static string FlowsheetFormActivity_UddInstanceId {
            get {
                return ResourceManager.GetString("FlowsheetFormActivity_UddInstanceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of days since this value was recorded..
        /// </summary>
        internal static string FlowsheetLookupActivity_AgeInDays_Description {
            get {
                return ResourceManager.GetString("FlowsheetLookupActivity_AgeInDays_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observation Age (Days).
        /// </summary>
        internal static string FlowsheetLookupActivity_AgeInDays_DisplayName {
            get {
                return ResourceManager.GetString("FlowsheetLookupActivity_AgeInDays_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of hours since this value was recorded..
        /// </summary>
        internal static string FlowsheetLookupActivity_AgeInHours_Description {
            get {
                return ResourceManager.GetString("FlowsheetLookupActivity_AgeInHours_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observation Age (Hours).
        /// </summary>
        internal static string FlowsheetLookupActivity_AgeInHours_DisplayName {
            get {
                return ResourceManager.GetString("FlowsheetLookupActivity_AgeInHours_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flowsheet Lookup.
        /// </summary>
        internal static string FlowsheetLookupActivity_DisplayName {
            get {
                return ResourceManager.GetString("FlowsheetLookupActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configures to pull the earliest value, latest value, or value by the Obr_Id provided..
        /// </summary>
        internal static string FlowsheetLookupActivity_LookupMethod_Description {
            get {
                return ResourceManager.GetString("FlowsheetLookupActivity_LookupMethod_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookup Method.
        /// </summary>
        internal static string FlowsheetLookupActivity_LookupMethod_DisplayName {
            get {
                return ResourceManager.GetString("FlowsheetLookupActivity_LookupMethod_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data or tablie item to lookup from the flowsheet..
        /// </summary>
        internal static string FlowsheetLookupActivity_ObdGuid_Description {
            get {
                return ResourceManager.GetString("FlowsheetLookupActivity_ObdGuid_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observation Item (Data or Table).
        /// </summary>
        internal static string FlowsheetLookupActivity_ObdGuid_DisplayName {
            get {
                return ResourceManager.GetString("FlowsheetLookupActivity_ObdGuid_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The primary key of the ObsReq record to retreive the value from..
        /// </summary>
        internal static string FlowsheetLookupActivity_ObrId_Description {
            get {
                return ResourceManager.GetString("FlowsheetLookupActivity_ObrId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obr_Id.
        /// </summary>
        internal static string FlowsheetLookupActivity_ObrId_DisplayName {
            get {
                return ResourceManager.GetString("FlowsheetLookupActivity_ObrId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The observation value returned if the data type is a checkbox value.  Null otherwise..
        /// </summary>
        internal static string FlowsheetLookupActivity_ObsCheckboxValue_Description {
            get {
                return ResourceManager.GetString("FlowsheetLookupActivity_ObsCheckboxValue_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data (CheckBox).
        /// </summary>
        internal static string FlowsheetLookupActivity_ObsCheckboxValue_DisplayName {
            get {
                return ResourceManager.GetString("FlowsheetLookupActivity_ObsCheckboxValue_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Obd_Guid value of the observation value selected if the data type is a choice.  Null otherwise..
        /// </summary>
        internal static string FlowsheetLookupActivity_ObsChoiceValue_Description {
            get {
                return ResourceManager.GetString("FlowsheetLookupActivity_ObsChoiceValue_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data (Choice).
        /// </summary>
        internal static string FlowsheetLookupActivity_ObsChoiceValue_DisplayName {
            get {
                return ResourceManager.GetString("FlowsheetLookupActivity_ObsChoiceValue_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data type of the observation value..
        /// </summary>
        internal static string FlowsheetLookupActivity_ObsDataValueFormat_Description {
            get {
                return ResourceManager.GetString("FlowsheetLookupActivity_ObsDataValueFormat_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observation Data Type.
        /// </summary>
        internal static string FlowsheetLookupActivity_ObsDataValueFormat_DisplayName {
            get {
                return ResourceManager.GetString("FlowsheetLookupActivity_ObsDataValueFormat_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The observation value returned if the data type is date or a time.  Null otherwise..
        /// </summary>
        internal static string FlowsheetLookupActivity_ObsDateTimeValue_Description {
            get {
                return ResourceManager.GetString("FlowsheetLookupActivity_ObsDateTimeValue_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data (Date and Time).
        /// </summary>
        internal static string FlowsheetLookupActivity_ObsDateTimeValue_DisplayName {
            get {
                return ResourceManager.GetString("FlowsheetLookupActivity_ObsDateTimeValue_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date and time the observation was taken..
        /// </summary>
        internal static string FlowsheetLookupActivity_ObsDtTm_Description {
            get {
                return ResourceManager.GetString("FlowsheetLookupActivity_ObsDtTm_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observation Date/Time.
        /// </summary>
        internal static string FlowsheetLookupActivity_ObsDtTm_DisplayName {
            get {
                return ResourceManager.GetString("FlowsheetLookupActivity_ObsDtTm_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observation item not found.
        /// </summary>
        internal static string FlowsheetLookupActivity_ObservationItemNotFound {
            get {
                return ResourceManager.GetString("FlowsheetLookupActivity_ObservationItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The observation value returned if the data type is numeric.  Null otherwise..
        /// </summary>
        internal static string FlowsheetLookupActivity_ObsNumericValue_Description {
            get {
                return ResourceManager.GetString("FlowsheetLookupActivity_ObsNumericValue_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data (Numeric).
        /// </summary>
        internal static string FlowsheetLookupActivity_ObsNumericValue_DisplayName {
            get {
                return ResourceManager.GetString("FlowsheetLookupActivity_ObsNumericValue_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True if a result found.  False otherwise..
        /// </summary>
        internal static string FlowsheetLookupActivity_ObsResultFound_Description {
            get {
                return ResourceManager.GetString("FlowsheetLookupActivity_ObsResultFound_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observation Result Found.
        /// </summary>
        internal static string FlowsheetLookupActivity_ObsResultFound_DisplayName {
            get {
                return ResourceManager.GetString("FlowsheetLookupActivity_ObsResultFound_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The observation value returned if the data type is a string.  Null otherwise..
        /// </summary>
        internal static string FlowsheetLookupActivity_ObsStringValue_Description {
            get {
                return ResourceManager.GetString("FlowsheetLookupActivity_ObsStringValue_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data (String).
        /// </summary>
        internal static string FlowsheetLookupActivity_ObsStringValue_DisplayName {
            get {
                return ResourceManager.GetString("FlowsheetLookupActivity_ObsStringValue_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The patient of the flowsheet value belongs to..
        /// </summary>
        internal static string FlowsheetLookupActivity_PatId1_Description {
            get {
                return ResourceManager.GetString("FlowsheetLookupActivity_PatId1_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        internal static string FlowsheetLookupActivity_PatId1_DisplayName {
            get {
                return ResourceManager.GetString("FlowsheetLookupActivity_PatId1_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Items Format.
        /// </summary>
        internal static string FlowsheetMergeFieldActivity_DataItemsFormat_Description {
            get {
                return ResourceManager.GetString("FlowsheetMergeFieldActivity_DataItemsFormat_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Items Format.
        /// </summary>
        internal static string FlowsheetMergeFieldActivity_DataItemsFormat_DisplayName {
            get {
                return ResourceManager.GetString("FlowsheetMergeFieldActivity_DataItemsFormat_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string FlowsheetMergeFieldActivity_Date {
            get {
                return ResourceManager.GetString("FlowsheetMergeFieldActivity_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range of dates to retrieve records over.
        /// </summary>
        internal static string FlowsheetMergeFieldActivity_DateRange_Description {
            get {
                return ResourceManager.GetString("FlowsheetMergeFieldActivity_DateRange_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Range.
        /// </summary>
        internal static string FlowsheetMergeFieldActivity_DateRange_DisplayName {
            get {
                return ResourceManager.GetString("FlowsheetMergeFieldActivity_DateRange_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flowsheet Merge Field.
        /// </summary>
        internal static string FlowsheetMergeFieldActivity_DisplayName {
            get {
                return ResourceManager.GetString("FlowsheetMergeFieldActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heading.
        /// </summary>
        internal static string FlowsheetMergeFieldActivity_Heading {
            get {
                return ResourceManager.GetString("FlowsheetMergeFieldActivity_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose to hide data items, folders, or neither if empty.
        /// </summary>
        internal static string FlowsheetMergeFieldActivity_HideIfBlank_Description {
            get {
                return ResourceManager.GetString("FlowsheetMergeFieldActivity_HideIfBlank_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide If Blank.
        /// </summary>
        internal static string FlowsheetMergeFieldActivity_HideIfBlank_DisplayName {
            get {
                return ResourceManager.GetString("FlowsheetMergeFieldActivity_HideIfBlank_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Html.
        /// </summary>
        internal static string FlowsheetMergeFieldActivity_Html_Description {
            get {
                return ResourceManager.GetString("FlowsheetMergeFieldActivity_Html_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Html.
        /// </summary>
        internal static string FlowsheetMergeFieldActivity_Html_DisplayName {
            get {
                return ResourceManager.GetString("FlowsheetMergeFieldActivity_Html_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incude Instructions.
        /// </summary>
        internal static string FlowsheetMergeFieldActivity_IncludeInstructions_Description {
            get {
                return ResourceManager.GetString("FlowsheetMergeFieldActivity_IncludeInstructions_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Instructions.
        /// </summary>
        internal static string FlowsheetMergeFieldActivity_IncludeInstructions_DisplayName {
            get {
                return ResourceManager.GetString("FlowsheetMergeFieldActivity_IncludeInstructions_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions.
        /// </summary>
        internal static string FlowsheetMergeFieldActivity_Instructions {
            get {
                return ResourceManager.GetString("FlowsheetMergeFieldActivity_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of records to display for &quot;Last N Records...&quot; date range values..
        /// </summary>
        internal static string FlowsheetMergeFieldActivity_NumberOfRecords_Description {
            get {
                return ResourceManager.GetString("FlowsheetMergeFieldActivity_NumberOfRecords_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Records.
        /// </summary>
        internal static string FlowsheetMergeFieldActivity_NumberOfRecords_DisplayName {
            get {
                return ResourceManager.GetString("FlowsheetMergeFieldActivity_NumberOfRecords_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of OBR_SET_IDs to be used for displaying specific user data.
        /// </summary>
        internal static string FlowsheetMergeFieldActivity_ObrSetIds_Description {
            get {
                return ResourceManager.GetString("FlowsheetMergeFieldActivity_ObrSetIds_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ObrSetIds.
        /// </summary>
        internal static string FlowsheetMergeFieldActivity_ObrSetIds_DisplayName {
            get {
                return ResourceManager.GetString("FlowsheetMergeFieldActivity_ObrSetIds_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary of ObsReq DateTime (key) and Entity (value).
        /// </summary>
        internal static string FlowsheetMergeFieldActivity_ObsReqsByDate_Description {
            get {
                return ResourceManager.GetString("FlowsheetMergeFieldActivity_ObsReqsByDate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ObsReqs by Date.
        /// </summary>
        internal static string FlowsheetMergeFieldActivity_ObsReqsByDate_DisplayName {
            get {
                return ResourceManager.GetString("FlowsheetMergeFieldActivity_ObsReqsByDate_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Date.
        /// </summary>
        internal static string FlowsheetMergeFieldActivity_OrderDate {
            get {
                return ResourceManager.GetString("FlowsheetMergeFieldActivity_OrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Description.
        /// </summary>
        internal static string FlowsheetMergeFieldActivity_OrderDescription {
            get {
                return ResourceManager.GetString("FlowsheetMergeFieldActivity_OrderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Format.
        /// </summary>
        internal static string FlowsheetMergeFieldActivity_OutputFormat_Description {
            get {
                return ResourceManager.GetString("FlowsheetMergeFieldActivity_OutputFormat_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Format.
        /// </summary>
        internal static string FlowsheetMergeFieldActivity_OutputFormat_DisplayName {
            get {
                return ResourceManager.GetString("FlowsheetMergeFieldActivity_OutputFormat_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delimiter for Paragraph Format.
        /// </summary>
        internal static string FlowsheetMergeFieldActivity_ParagraphDelimiter_Description {
            get {
                return ResourceManager.GetString("FlowsheetMergeFieldActivity_ParagraphDelimiter_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delimiter for Paragraph Format.
        /// </summary>
        internal static string FlowsheetMergeFieldActivity_ParagraphDelimiter_DisplayName {
            get {
                return ResourceManager.GetString("FlowsheetMergeFieldActivity_ParagraphDelimiter_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pat ID1.
        /// </summary>
        internal static string FlowsheetMergeFieldActivity_PatId1_Description {
            get {
                return ResourceManager.GetString("FlowsheetMergeFieldActivity_PatId1_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pat ID1.
        /// </summary>
        internal static string FlowsheetMergeFieldActivity_PatId1_DisplayName {
            get {
                return ResourceManager.GetString("FlowsheetMergeFieldActivity_PatId1_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plain Text.
        /// </summary>
        internal static string FlowsheetMergeFieldActivity_PlainText_Description {
            get {
                return ResourceManager.GetString("FlowsheetMergeFieldActivity_PlainText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plain Text.
        /// </summary>
        internal static string FlowsheetMergeFieldActivity_PlainText_DisplayName {
            get {
                return ResourceManager.GetString("FlowsheetMergeFieldActivity_PlainText_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Items.
        /// </summary>
        internal static string FlowsheetMergeFieldActivity_SelectedItems_Description {
            get {
                return ResourceManager.GetString("FlowsheetMergeFieldActivity_SelectedItems_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Items.
        /// </summary>
        internal static string FlowsheetMergeFieldActivity_SelectedItems_DisplayName {
            get {
                return ResourceManager.GetString("FlowsheetMergeFieldActivity_SelectedItems_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach date to record data item if in list or paragraph output format..
        /// </summary>
        internal static string FlowsheetMergeFieldActivity_ShowDate_Description {
            get {
                return ResourceManager.GetString("FlowsheetMergeFieldActivity_ShowDate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Date.
        /// </summary>
        internal static string FlowsheetMergeFieldActivity_ShowDate_DisplayName {
            get {
                return ResourceManager.GetString("FlowsheetMergeFieldActivity_ShowDate_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Order.
        /// </summary>
        internal static string FlowsheetMergeFieldActivity_ShowOrder_Description {
            get {
                return ResourceManager.GetString("FlowsheetMergeFieldActivity_ShowOrder_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Order.
        /// </summary>
        internal static string FlowsheetMergeFieldActivity_ShowOrder_DisplayName {
            get {
                return ResourceManager.GetString("FlowsheetMergeFieldActivity_ShowOrder_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show voided assessments.
        /// </summary>
        internal static string FlowsheetMergeFieldActivity_ShowVoided_Description {
            get {
                return ResourceManager.GetString("FlowsheetMergeFieldActivity_ShowVoided_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Voided.
        /// </summary>
        internal static string FlowsheetMergeFieldActivity_ShowVoided_DisplayName {
            get {
                return ResourceManager.GetString("FlowsheetMergeFieldActivity_ShowVoided_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record date.
        /// </summary>
        internal static string FlowsheetMergeFieldActivity_SingleRecordParagraphListDateHeader {
            get {
                return ResourceManager.GetString("FlowsheetMergeFieldActivity_SingleRecordParagraphListDateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff.
        /// </summary>
        internal static string FlowsheetMergeFieldActivity_Staff_Description {
            get {
                return ResourceManager.GetString("FlowsheetMergeFieldActivity_Staff_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff.
        /// </summary>
        internal static string FlowsheetMergeFieldActivity_Staff_DisplayName {
            get {
                return ResourceManager.GetString("FlowsheetMergeFieldActivity_Staff_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string FlowsheetMergeFieldActivity_Status {
            get {
                return ResourceManager.GetString("FlowsheetMergeFieldActivity_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statused By.
        /// </summary>
        internal static string FlowsheetMergeFieldActivity_StatusBy_FullName {
            get {
                return ResourceManager.GetString("FlowsheetMergeFieldActivity_StatusBy_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statused By.
        /// </summary>
        internal static string FlowsheetMergeFieldActivity_StatusBy_Initials {
            get {
                return ResourceManager.GetString("FlowsheetMergeFieldActivity_StatusBy_Initials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Date.
        /// </summary>
        internal static string FlowsheetMergeFieldActivity_StatusDate {
            get {
                return ResourceManager.GetString("FlowsheetMergeFieldActivity_StatusDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Info.
        /// </summary>
        internal static string FlowsheetMergeFieldActivity_StatusInfo_Description {
            get {
                return ResourceManager.GetString("FlowsheetMergeFieldActivity_StatusInfo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Info.
        /// </summary>
        internal static string FlowsheetMergeFieldActivity_StatusInfo_DisplayName {
            get {
                return ResourceManager.GetString("FlowsheetMergeFieldActivity_StatusInfo_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Items Format.
        /// </summary>
        internal static string FlowsheetMergeFieldActivity_TableItemsFormat_Description {
            get {
                return ResourceManager.GetString("FlowsheetMergeFieldActivity_TableItemsFormat_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Items Format.
        /// </summary>
        internal static string FlowsheetMergeFieldActivity_TableItemsFormat_DisplayName {
            get {
                return ResourceManager.GetString("FlowsheetMergeFieldActivity_TableItemsFormat_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Name.
        /// </summary>
        internal static string FlowsheetMergeFieldActivity_TestName {
            get {
                return ResourceManager.GetString("FlowsheetMergeFieldActivity_TestName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string FlowsheetMergeFieldActivity_Time {
            get {
                return ResourceManager.GetString("FlowsheetMergeFieldActivity_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values.
        /// </summary>
        internal static string FlowsheetMergeFieldActivity_Values_Description {
            get {
                return ResourceManager.GetString("FlowsheetMergeFieldActivity_Values_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values.
        /// </summary>
        internal static string FlowsheetMergeFieldActivity_Values_DisplayName {
            get {
                return ResourceManager.GetString("FlowsheetMergeFieldActivity_Values_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Charting.
        /// </summary>
        internal static string GeneralCharting_ActivityGroup {
            get {
                return ResourceManager.GetString("GeneralCharting_ActivityGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current BSA value found for this patient..
        /// </summary>
        internal static string GetCurrentBSAActivity_BSA_Description {
            get {
                return ResourceManager.GetString("GetCurrentBSAActivity_BSA_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BSA.
        /// </summary>
        internal static string GetCurrentBSAActivity_BSA_DisplayName {
            get {
                return ResourceManager.GetString("GetCurrentBSAActivity_BSA_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Current BSA.
        /// </summary>
        internal static string GetCurrentBSAActivity_DisplayName {
            get {
                return ResourceManager.GetString("GetCurrentBSAActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines whether pharmacy orders from today should be included when determining the current BSA..
        /// </summary>
        internal static string GetCurrentBSAActivity_IncludeOrders_Description {
            get {
                return ResourceManager.GetString("GetCurrentBSAActivity_IncludeOrders_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Orders.
        /// </summary>
        internal static string GetCurrentBSAActivity_IncludeOrders_DisplayName {
            get {
                return ResourceManager.GetString("GetCurrentBSAActivity_IncludeOrders_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The primary key of the patient whose BSA is being looked up..
        /// </summary>
        internal static string GetCurrentBSAActivity_PatId1_Description {
            get {
                return ResourceManager.GetString("GetCurrentBSAActivity_PatId1_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        internal static string GetCurrentBSAActivity_PatId1_DisplayName {
            get {
                return ResourceManager.GetString("GetCurrentBSAActivity_PatId1_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional context value which will be added to the order&apos;s clinical detail..
        /// </summary>
        internal static string GetOrderClinicalDetailActivity_ContextValue_Description {
            get {
                return ResourceManager.GetString("GetOrderClinicalDetailActivity_ContextValue_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context Value.
        /// </summary>
        internal static string GetOrderClinicalDetailActivity_ContextValue_DisplayName {
            get {
                return ResourceManager.GetString("GetOrderClinicalDetailActivity_ContextValue_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Order Clinical Detail.
        /// </summary>
        internal static string GetOrderClinicalDetailActivity_DisplayName {
            get {
                return ResourceManager.GetString("GetOrderClinicalDetailActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The set id of the order to return clinical detail for..
        /// </summary>
        internal static string GetOrderClinicalDetailActivity_OrcSetId_Description {
            get {
                return ResourceManager.GetString("GetOrderClinicalDetailActivity_OrcSetId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orc Set Id.
        /// </summary>
        internal static string GetOrderClinicalDetailActivity_OrcSetId_DisplayName {
            get {
                return ResourceManager.GetString("GetOrderClinicalDetailActivity_OrcSetId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An XML string representing the clinical detail of an order..
        /// </summary>
        internal static string GetOrderClinicalDetailActivity_Result_Description {
            get {
                return ResourceManager.GetString("GetOrderClinicalDetailActivity_Result_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string GetOrderClinicalDetailActivity_Result_DisplayName {
            get {
                return ResourceManager.GetString("GetOrderClinicalDetailActivity_Result_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions.
        /// </summary>
        internal static string Instructions {
            get {
                return ResourceManager.GetString("Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intent Browse.
        /// </summary>
        internal static string IntentBrowseActivity_DisplayName {
            get {
                return ResourceManager.GetString("IntentBrowseActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The primary key value of the selected intent.
        /// </summary>
        internal static string IntentBrowseActivity_Prompt_Pro_Id_Description {
            get {
                return ResourceManager.GetString("IntentBrowseActivity_Prompt_Pro_Id_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text value of the selected intent (SelectedText).
        /// </summary>
        internal static string IntentBrowseActivity_SelectedText_Description {
            get {
                return ResourceManager.GetString("IntentBrowseActivity_SelectedText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Text.
        /// </summary>
        internal static string IntentBrowseActivity_SelectedText_DisplayName {
            get {
                return ResourceManager.GetString("IntentBrowseActivity_SelectedText_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns.
        /// </summary>
        internal static string MergeFieldFormatterActivity_Columns_Description {
            get {
                return ResourceManager.GetString("MergeFieldFormatterActivity_Columns_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns.
        /// </summary>
        internal static string MergeFieldFormatterActivity_Columns_DisplayName {
            get {
                return ResourceManager.GetString("MergeFieldFormatterActivity_Columns_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge Field Formatter.
        /// </summary>
        internal static string MergeFieldFormatterActivity_DisplayName {
            get {
                return ResourceManager.GetString("MergeFieldFormatterActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Data.
        /// </summary>
        internal static string MergeFieldFormatterActivity_FieldData_Description {
            get {
                return ResourceManager.GetString("MergeFieldFormatterActivity_FieldData_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Data.
        /// </summary>
        internal static string MergeFieldFormatterActivity_FieldData_DisplayName {
            get {
                return ResourceManager.GetString("MergeFieldFormatterActivity_FieldData_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Html.
        /// </summary>
        internal static string MergeFieldFormatterActivity_Html_Description {
            get {
                return ResourceManager.GetString("MergeFieldFormatterActivity_Html_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Html.
        /// </summary>
        internal static string MergeFieldFormatterActivity_Html_DisplayName {
            get {
                return ResourceManager.GetString("MergeFieldFormatterActivity_Html_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Format.
        /// </summary>
        internal static string MergeFieldFormatterActivity_OutputFormat_Description {
            get {
                return ResourceManager.GetString("MergeFieldFormatterActivity_OutputFormat_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Format.
        /// </summary>
        internal static string MergeFieldFormatterActivity_OutputFormat_DisplayName {
            get {
                return ResourceManager.GetString("MergeFieldFormatterActivity_OutputFormat_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plain Text.
        /// </summary>
        internal static string MergeFieldFormatterActivity_PlainText_Description {
            get {
                return ResourceManager.GetString("MergeFieldFormatterActivity_PlainText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plain Text.
        /// </summary>
        internal static string MergeFieldFormatterActivity_PlainText_DisplayName {
            get {
                return ResourceManager.GetString("MergeFieldFormatterActivity_PlainText_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a new eScribe document using the specified template and merges the specified imported document in it.
        /// </summary>
        internal static string MergeInboundDocumentActivity_Description {
            get {
                return ResourceManager.GetString("MergeInboundDocumentActivity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge Inbound Document.
        /// </summary>
        internal static string MergeInboundDocumentActivity_DisplayName {
            get {
                return ResourceManager.GetString("MergeInboundDocumentActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object ID.
        /// </summary>
        internal static string MergeInboundDocumentActivity_ObjId_Description {
            get {
                return ResourceManager.GetString("MergeInboundDocumentActivity_ObjId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object ID.
        /// </summary>
        internal static string MergeInboundDocumentActivity_ObjId_DisplayName {
            get {
                return ResourceManager.GetString("MergeInboundDocumentActivity_ObjId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eScribe template to use.
        /// </summary>
        internal static string MergeInboundDocumentActivity_Template_Description {
            get {
                return ResourceManager.GetString("MergeInboundDocumentActivity_Template_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        internal static string MergeInboundDocumentActivity_Template_DisplayName {
            get {
                return ResourceManager.GetString("MergeInboundDocumentActivity_Template_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        internal static string Orders_Category {
            get {
                return ResourceManager.GetString("Orders_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save current data?.
        /// </summary>
        internal static string SaveCurrentData {
            get {
                return ResourceManager.GetString("SaveCurrentData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status_Enum.
        /// </summary>
        internal static string Status_Enum {
            get {
                return ResourceManager.GetString("Status_Enum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
