//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impac.Mosaiq.IQ.Activities.MedOnc {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Impac.Mosaiq.IQ.Activities.MedOnc.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The calculation factor being accepted for this order..
        /// </summary>
        internal static string AcceptCalcFactorActivity_AcceptedCalcFactor_Description {
            get {
                return ResourceManager.GetString("AcceptCalcFactorActivity_AcceptedCalcFactor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted Calculation Factor.
        /// </summary>
        internal static string AcceptCalcFactorActivity_AcceptedCalcFactor_DisplayName {
            get {
                return ResourceManager.GetString("AcceptCalcFactorActivity_AcceptedCalcFactor_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept Calculation Factor.
        /// </summary>
        internal static string AcceptCalcFactorActivity_DisplayName {
            get {
                return ResourceManager.GetString("AcceptCalcFactorActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Rxo_Set_Id of the pharmacy order which the accepted calculation factor applies to..
        /// </summary>
        internal static string AcceptCalcFactorActivity_RxoSetId_Description {
            get {
                return ResourceManager.GetString("AcceptCalcFactorActivity_RxoSetId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rxo_Set_Id.
        /// </summary>
        internal static string AcceptCalcFactorActivity_RxoSetId_DisplayName {
            get {
                return ResourceManager.GetString("AcceptCalcFactorActivity_RxoSetId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation factor variance value accepted during pharmacy order approval processing.
        /// </summary>
        internal static string AcceptedVariance_Description {
            get {
                return ResourceManager.GetString("AcceptedVariance_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted Variance.
        /// </summary>
        internal static string AcceptedVariance_DisplayName {
            get {
                return ResourceManager.GetString("AcceptedVariance_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The calculation factor to be checked for acceptance..
        /// </summary>
        internal static string CheckCalcFactorActivity_CalcFactor_Description {
            get {
                return ResourceManager.GetString("CheckCalcFactorActivity_CalcFactor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation Factor.
        /// </summary>
        internal static string CheckCalcFactorActivity_CalcFactor_DisplayName {
            get {
                return ResourceManager.GetString("CheckCalcFactorActivity_CalcFactor_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Calculation Factor.
        /// </summary>
        internal static string CheckCalcFactorActivity_DisplayName {
            get {
                return ResourceManager.GetString("CheckCalcFactorActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns whether the calculation factor is within an accepted range..
        /// </summary>
        internal static string CheckCalcFactorActivity_Result_Description {
            get {
                return ResourceManager.GetString("CheckCalcFactorActivity_Result_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string CheckCalcFactorActivity_Result_DisplayName {
            get {
                return ResourceManager.GetString("CheckCalcFactorActivity_Result_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Rxo_Set_Id of the pharmacy order to check..
        /// </summary>
        internal static string CheckCalcFactorActivity_RxoSetId_Description {
            get {
                return ResourceManager.GetString("CheckCalcFactorActivity_RxoSetId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rxo_Set_Id.
        /// </summary>
        internal static string CheckCalcFactorActivity_RxoSetId_DisplayName {
            get {
                return ResourceManager.GetString("CheckCalcFactorActivity_RxoSetId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Dose Allowed.
        /// </summary>
        internal static string CheckDoseAllowedActivity_DisplayName {
            get {
                return ResourceManager.GetString("CheckDoseAllowedActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dose being checked to see if it’s allowed..
        /// </summary>
        internal static string CheckDoseAllowedActivity_Dose_Description {
            get {
                return ResourceManager.GetString("CheckDoseAllowedActivity_Dose_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dose.
        /// </summary>
        internal static string CheckDoseAllowedActivity_Dose_DisplayName {
            get {
                return ResourceManager.GetString("CheckDoseAllowedActivity_Dose_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The primary key of the drug.
        /// </summary>
        internal static string CheckDoseAllowedActivity_Drg_Id_Description {
            get {
                return ResourceManager.GetString("CheckDoseAllowedActivity_Drg_Id_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns whether the dose is allowed..
        /// </summary>
        internal static string CheckDoseAllowedActivity_Result_Description {
            get {
                return ResourceManager.GetString("CheckDoseAllowedActivity_Result_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string CheckDoseAllowedActivity_Result_DisplayName {
            get {
                return ResourceManager.GetString("CheckDoseAllowedActivity_Result_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dose Adjustment Form.
        /// </summary>
        internal static string DoseAdjustFormActivity_DisplayName {
            get {
                return ResourceManager.GetString("DoseAdjustFormActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Set_Id of the order being adjusted.
        /// </summary>
        internal static string DoseAdjustFormActivity_Orc_Set_Id_Description {
            get {
                return ResourceManager.GetString("DoseAdjustFormActivity_Orc_Set_Id_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orc_Set_Id.
        /// </summary>
        internal static string DoseAdjustFormActivity_Orc_Set_Id_DisplayName {
            get {
                return ResourceManager.GetString("DoseAdjustFormActivity_Orc_Set_Id_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True if the user clicks OK, false otherwise..
        /// </summary>
        internal static string DoseAdjustFormActivity_Result_Description {
            get {
                return ResourceManager.GetString("DoseAdjustFormActivity_Result_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string DoseAdjustFormActivity_Result_DisplayName {
            get {
                return ResourceManager.GetString("DoseAdjustFormActivity_Result_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates whether the form should simulate a click to the &quot;Use Recent BSA&quot; button before the window displays..
        /// </summary>
        internal static string DoseAdjustFormActivity_UseRecentBSA_Description {
            get {
                return ResourceManager.GetString("DoseAdjustFormActivity_UseRecentBSA_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Recent BSA.
        /// </summary>
        internal static string DoseAdjustFormActivity_UseRecentBSA_DisplayName {
            get {
                return ResourceManager.GetString("DoseAdjustFormActivity_UseRecentBSA_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drg_Id.
        /// </summary>
        internal static string Drg_Id_DisplayName {
            get {
                return ResourceManager.GetString("Drg_Id_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Accepted Calculation Factor Variance.
        /// </summary>
        internal static string GetAcceptedCalcFactorVarianceActivity_DisplayName {
            get {
                return ResourceManager.GetString("GetAcceptedCalcFactorVarianceActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The calculation factor (BSA, weight, etc) used to calculate the suggested dose..
        /// </summary>
        internal static string GetSuggestedDoseActivity_CalcFactor_Description {
            get {
                return ResourceManager.GetString("GetSuggestedDoseActivity_CalcFactor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation Factor.
        /// </summary>
        internal static string GetSuggestedDoseActivity_CalcFactor_DisplayName {
            get {
                return ResourceManager.GetString("GetSuggestedDoseActivity_CalcFactor_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Suggested Dose.
        /// </summary>
        internal static string GetSuggestedDoseActivity_DisplayName {
            get {
                return ResourceManager.GetString("GetSuggestedDoseActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The primary key of the PharmOrd record we want to get the suggested dose for..
        /// </summary>
        internal static string GetSuggestedDoseActivity_Rxo_Id_Description {
            get {
                return ResourceManager.GetString("GetSuggestedDoseActivity_Rxo_Id_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rxo_Id.
        /// </summary>
        internal static string GetSuggestedDoseActivity_Rxo_Id_DisplayName {
            get {
                return ResourceManager.GetString("GetSuggestedDoseActivity_Rxo_Id_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The suggsted dose calculated from the dose basis on the PharmOrd record and the calculation factor passed in..
        /// </summary>
        internal static string GetSuggestedDoseActivity_SuggestedDose_Description {
            get {
                return ResourceManager.GetString("GetSuggestedDoseActivity_SuggestedDose_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggested Dose.
        /// </summary>
        internal static string GetSuggestedDoseActivity_SuggestedDose_DisplayName {
            get {
                return ResourceManager.GetString("GetSuggestedDoseActivity_SuggestedDose_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dose which will be allowed within the currently executing batch of orders..
        /// </summary>
        internal static string MarkDoseAllowedActivity_AllowedDose_Description {
            get {
                return ResourceManager.GetString("MarkDoseAllowedActivity_AllowedDose_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed Dose.
        /// </summary>
        internal static string MarkDoseAllowedActivity_AllowedDose_DisplayName {
            get {
                return ResourceManager.GetString("MarkDoseAllowedActivity_AllowedDose_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark Dose Allowed.
        /// </summary>
        internal static string MarkDoseAllowedActivity_DisplayName {
            get {
                return ResourceManager.GetString("MarkDoseAllowedActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The primary key of the drug for which the dose is being allowed.
        /// </summary>
        internal static string MarkDoseAllowedActivity_Drg_Id_Description {
            get {
                return ResourceManager.GetString("MarkDoseAllowedActivity_Drg_Id_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Oncology.
        /// </summary>
        internal static string MedOnc_ActivityGroup {
            get {
                return ResourceManager.GetString("MedOnc_ActivityGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pharmacy Orders.
        /// </summary>
        internal static string PharmOrd_Category {
            get {
                return ResourceManager.GetString("PharmOrd_Category", resourceCulture);
            }
        }
    }
}
