//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impac.Mosaiq.IQ.Activities.Variables {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NTStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NTStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Impac.Mosaiq.IQ.Activities.Variables.NTStrings", typeof(NTStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impac.Mosaiq.Widgets.General.CarePlanWidgets.
        /// </summary>
        internal static string IQCareplanVarActivity_CarePlanBroweseWidget_AssemblyName {
            get {
                return ResourceManager.GetString("IQCareplanVarActivity_CarePlanBroweseWidget_AssemblyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CarePlanBrowseWidget.
        /// </summary>
        internal static string IQCareplanVarActivity_CarePlanBrowseWidget_ClassName {
            get {
                return ResourceManager.GetString("IQCareplanVarActivity_CarePlanBrowseWidget_ClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CarePlanSelection.
        /// </summary>
        internal static string IQCareplanVarActivity_CarePlanBrowseWidget_InstanceName {
            get {
                return ResourceManager.GetString("IQCareplanVarActivity_CarePlanBrowseWidget_InstanceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impac.Mosaiq.UI.InputTemplatesWindows.
        /// </summary>
        internal static string IQQclTaskVarActivity_QclTaskBrowse_AssemblyName {
            get {
                return ResourceManager.GetString("IQQclTaskVarActivity_QclTaskBrowse_AssemblyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckSecurity.
        /// </summary>
        internal static string IQQclTaskVarActivity_QclTaskBrowse_CD_CheckSecurity {
            get {
                return ResourceManager.GetString("IQQclTaskVarActivity_QclTaskBrowse_CD_CheckSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoEdit.
        /// </summary>
        internal static string IQQclTaskVarActivity_QclTaskBrowse_CD_NoEdit {
            get {
                return ResourceManager.GetString("IQQclTaskVarActivity_QclTaskBrowse_CD_NoEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QCLTaskBrowse.
        /// </summary>
        internal static string IQQclTaskVarActivity_QclTaskBrowse_ClassName {
            get {
                return ResourceManager.GetString("IQQclTaskVarActivity_QclTaskBrowse_ClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QCLTaskSelection.
        /// </summary>
        internal static string IQQclTaskVarActivity_QclTaskBrowse_InstanceName {
            get {
                return ResourceManager.GetString("IQQclTaskVarActivity_QclTaskBrowse_InstanceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impac.Mosaiq.UI.InputTemplatesWindows.
        /// </summary>
        internal static string IQStaffLocVarActivity_StaffBrowseWidget_AssemblyName {
            get {
                return ResourceManager.GetString("IQStaffLocVarActivity_StaffBrowseWidget_AssemblyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StaffQBrowse.
        /// </summary>
        internal static string IQStaffLocVarActivity_StaffBrowseWidget_ClassName {
            get {
                return ResourceManager.GetString("IQStaffLocVarActivity_StaffBrowseWidget_ClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StaffLocBrowse.
        /// </summary>
        internal static string IQStaffLocVarActivity_StaffBrowseWidget_InstanceName {
            get {
                return ResourceManager.GetString("IQStaffLocVarActivity_StaffBrowseWidget_InstanceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string IQStaffLocVarActivity_StaffBrowseWidget_Properties {
            get {
                return ResourceManager.GetString("IQStaffLocVarActivity_StaffBrowseWidget_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impac.Mosaiq.UI.InputTemplatesWindows.
        /// </summary>
        internal static string IQStaffVarActivity_StaffBrowseWidget_AssemblyName {
            get {
                return ResourceManager.GetString("IQStaffVarActivity_StaffBrowseWidget_AssemblyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StaffQBrowse.
        /// </summary>
        internal static string IQStaffVarActivity_StaffBrowseWidget_ClassName {
            get {
                return ResourceManager.GetString("IQStaffVarActivity_StaffBrowseWidget_ClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StaffBrowse.
        /// </summary>
        internal static string IQStaffVarActivity_StaffBrowseWidget_InstanceName {
            get {
                return ResourceManager.GetString("IQStaffVarActivity_StaffBrowseWidget_InstanceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string IQStaffVarActivity_StaffBrowseWidget_Properties {
            get {
                return ResourceManager.GetString("IQStaffVarActivity_StaffBrowseWidget_Properties", resourceCulture);
            }
        }
    }
}
