//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impac.Mosaiq.IQ.Activities.Variables {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Impac.Mosaiq.IQ.Activities.Variables.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Multi-Line Editor.
        /// </summary>
        internal static string AllowMultipleLines_DisplayName {
            get {
                return ResourceManager.GetString("AllowMultipleLines_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Date Ranges.
        /// </summary>
        internal static string AvailableDateRanges_DisplayName {
            get {
                return ResourceManager.GetString("AvailableDateRanges_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checklist Procedure.
        /// </summary>
        internal static string ChecklistProcedure {
            get {
                return ResourceManager.GetString("ChecklistProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinical-.
        /// </summary>
        internal static string ClinicalNotePrefix {
            get {
                return ResourceManager.GetString("ClinicalNotePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Type.
        /// </summary>
        internal static string DocumentType {
            get {
                return ResourceManager.GetString("DocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {ValueType:0} {Value:1} must be between {Min:2} and {Max:3}.
        /// </summary>
        internal static string DoubleMustBeBetween {
            get {
                return ResourceManager.GetString("DoubleMustBeBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {ValueType:0} {Value:1} must be greater than {Min:2}.
        /// </summary>
        internal static string DoubleMustBeGreaterThan {
            get {
                return ResourceManager.GetString("DoubleMustBeGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {ValueType:0} {Value:1} must be less than {Max:2}.
        /// </summary>
        internal static string DoubleMustBeLessThan {
            get {
                return ResourceManager.GetString("DoubleMustBeLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        internal static string False {
            get {
                return ResourceManager.GetString("False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab Name.
        /// </summary>
        internal static string FlowsheetTab_DisplayName {
            get {
                return ResourceManager.GetString("FlowsheetTab_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Charting.
        /// </summary>
        internal static string GeneralCharting_Category {
            get {
                return ResourceManager.GetString("GeneralCharting_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Other Labs.
        /// </summary>
        internal static string IncludeOtherLabs_DisplayName {
            get {
                return ResourceManager.GetString("IncludeOtherLabs_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boolean.
        /// </summary>
        internal static string IQBooleanVarActivity_DisplayName {
            get {
                return ResourceManager.GetString("IQBooleanVarActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Care Plan.
        /// </summary>
        internal static string IQCareplanVarActivity_DisplayName {
            get {
                return ResourceManager.GetString("IQCareplanVarActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Careplan.
        /// </summary>
        internal static string IQCareplanVarActivity_WidgetTitle {
            get {
                return ResourceManager.GetString("IQCareplanVarActivity_WidgetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CDS Reference.
        /// </summary>
        internal static string IQCdsReferenceVarActivity_DisplayName {
            get {
                return ResourceManager.GetString("IQCdsReferenceVarActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Group.
        /// </summary>
        internal static string IQCodeGroupVarActivity_DisplayName {
            get {
                return ResourceManager.GetString("IQCodeGroupVarActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Item with Thresholds.
        /// </summary>
        internal static string IQDataItemThresholdsVarActivity_DisplayName {
            get {
                return ResourceManager.GetString("IQDataItemThresholdsVarActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed Data Item Types.
        /// </summary>
        internal static string IQDataItemVarActivity_AllowedDataItemTypes_DisplayName {
            get {
                return ResourceManager.GetString("IQDataItemVarActivity_AllowedDataItemTypes_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Table Titles.
        /// </summary>
        internal static string IQDataItemVarActivity_AllowTableTitles_DisplayName {
            get {
                return ResourceManager.GetString("IQDataItemVarActivity_AllowTableTitles_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0:ItemName}&apos; is not allowed.  Data Items are not allowed..
        /// </summary>
        internal static string IQDataItemVarActivity_DataItemsNotAllowed {
            get {
                return ResourceManager.GetString("IQDataItemVarActivity_DataItemsNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0:ItemName}&apos; is not allowed.  Allowed data item types are: {1:ItemList}.
        /// </summary>
        internal static string IQDataItemVarActivity_DataItemTypeNotAllowed {
            get {
                return ResourceManager.GetString("IQDataItemVarActivity_DataItemTypeNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flowsheet - Data Item or Table Title.
        /// </summary>
        internal static string IQDataItemVarActivity_DisplayName {
            get {
                return ResourceManager.GetString("IQDataItemVarActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0:ItemName}&apos; is not allowed.  Table titles are not allowed..
        /// </summary>
        internal static string IQDataItemVarActivity_TableTitlesNotAllowed {
            get {
                return ResourceManager.GetString("IQDataItemVarActivity_TableTitlesNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Range.
        /// </summary>
        internal static string IQDateRangeVarActivity_DisplayName {
            get {
                return ResourceManager.GetString("IQDateRangeVarActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string IQDateTimeVarActivity_DisplayName {
            get {
                return ResourceManager.GetString("IQDateTimeVarActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string IQDepartmentVarActivity_DisplayName {
            get {
                return ResourceManager.GetString("IQDepartmentVarActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnosis Code.
        /// </summary>
        internal static string IQDiagnosisCodeVarActivity_DisplayName {
            get {
                return ResourceManager.GetString("IQDiagnosisCodeVarActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Type.
        /// </summary>
        internal static string IQDocumentTypeVarActivity_DisplayName {
            get {
                return ResourceManager.GetString("IQDocumentTypeVarActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double.
        /// </summary>
        internal static string IQDoubleVarActivity_DisplayName {
            get {
                return ResourceManager.GetString("IQDoubleVarActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drug.
        /// </summary>
        internal static string IQDrugVarActivity_DisplayName {
            get {
                return ResourceManager.GetString("IQDrugVarActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumeration.
        /// </summary>
        internal static string IQEnumVarActivity_DisplayName {
            get {
                return ResourceManager.GetString("IQEnumVarActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preselected values with duplicate keys exist..
        /// </summary>
        internal static string IQEnumVarActivity_DuplicateKey {
            get {
                return ResourceManager.GetString("IQEnumVarActivity_DuplicateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;One or more preselected values are required&quot;.
        /// </summary>
        internal static string IQEnumVarActivity_PreselectedRequired {
            get {
                return ResourceManager.GetString("IQEnumVarActivity_PreselectedRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one preselected value must be defined..
        /// </summary>
        internal static string IQEnumVarActivity_PreselectedValueRequired {
            get {
                return ResourceManager.GetString("IQEnumVarActivity_PreselectedValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eSCRIBE Template.
        /// </summary>
        internal static string IQEscribeTemplateVarActivity_DisplayName {
            get {
                return ResourceManager.GetString("IQEscribeTemplateVarActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flowsheet Selection.
        /// </summary>
        internal static string IQFlowsheetVarActivity_DisplayName {
            get {
                return ResourceManager.GetString("IQFlowsheetVarActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab Name is not set.
        /// </summary>
        internal static string IQFlowsheetVarActivity_TabNameNotSet {
            get {
                return ResourceManager.GetString("IQFlowsheetVarActivity_TabNameNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integer.
        /// </summary>
        internal static string IQIntegerVarActivity_DisplayName {
            get {
                return ResourceManager.GetString("IQIntegerVarActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string IQLocationVarActivity_DisplayName {
            get {
                return ResourceManager.GetString("IQLocationVarActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note Type.
        /// </summary>
        internal static string IQNoteTypeVarActivity_DisplayName {
            get {
                return ResourceManager.GetString("IQNoteTypeVarActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Patient.
        /// </summary>
        internal static string IQPatientVarActivity_ActivePatient {
            get {
                return ResourceManager.GetString("IQPatientVarActivity_ActivePatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        internal static string IQPatientVarActivity_DisplayName {
            get {
                return ResourceManager.GetString("IQPatientVarActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure.
        /// </summary>
        internal static string IQProcedureVarActivity_DisplayName {
            get {
                return ResourceManager.GetString("IQProcedureVarActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QCL Task.
        /// </summary>
        internal static string IQQclTaskVarActivity_DisplayName {
            get {
                return ResourceManager.GetString("IQQclTaskVarActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Task.
        /// </summary>
        internal static string IQQclTaskVarActivity_WidgetTitle {
            get {
                return ResourceManager.GetString("IQQclTaskVarActivity_WidgetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff / Location.
        /// </summary>
        internal static string IQStaffLocVarActivity_DisplayName {
            get {
                return ResourceManager.GetString("IQStaffLocVarActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Staff/Loc.
        /// </summary>
        internal static string IQStaffLocVarActivity_WidgetTitle {
            get {
                return ResourceManager.GetString("IQStaffLocVarActivity_WidgetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Type or Category.
        /// </summary>
        internal static string IQStaffTypeOrCategoryVarActivity_DisplayName {
            get {
                return ResourceManager.GetString("IQStaffTypeOrCategoryVarActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Type.
        /// </summary>
        internal static string IQStaffTypeVarActivity_DisplayName {
            get {
                return ResourceManager.GetString("IQStaffTypeVarActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active User.
        /// </summary>
        internal static string IQStaffVarActivity_ActiveUser {
            get {
                return ResourceManager.GetString("IQStaffVarActivity_ActiveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff.
        /// </summary>
        internal static string IQStaffVarActivity_DisplayName {
            get {
                return ResourceManager.GetString("IQStaffVarActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Staff.
        /// </summary>
        internal static string IQStaffVarActivity_WidgetTitle {
            get {
                return ResourceManager.GetString("IQStaffVarActivity_WidgetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String.
        /// </summary>
        internal static string IQStringVarActivity_DisplayName {
            get {
                return ResourceManager.GetString("IQStringVarActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flowsheet - Table Item.
        /// </summary>
        internal static string IQTableItemVarActivity_DisplayName {
            get {
                return ResourceManager.GetString("IQTableItemVarActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Span (Relative).
        /// </summary>
        internal static string IQTimeSpanRelativeVarActivity_DisplayName {
            get {
                return ResourceManager.GetString("IQTimeSpanRelativeVarActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable Group.
        /// </summary>
        internal static string IQVarGroupActivity_DisplayName {
            get {
                return ResourceManager.GetString("IQVarGroupActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the activity in the designer and the name which will be displayed on the rounded group box surrounding each grid in the IQ Preferences Dialog..
        /// </summary>
        internal static string IQVarGroupActivity_DisplayName_Description {
            get {
                return ResourceManager.GetString("IQVarGroupActivity_DisplayName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines the display order of the variable groups in the IQ Script Preferences window..
        /// </summary>
        internal static string IQVarGroupActivity_DisplayOrder_Description {
            get {
                return ResourceManager.GetString("IQVarGroupActivity_DisplayOrder_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Order.
        /// </summary>
        internal static string IQVarGroupActivity_DisplayOrder_DisplayName {
            get {
                return ResourceManager.GetString("IQVarGroupActivity_DisplayOrder_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must have at least one child activity.
        /// </summary>
        internal static string IQVarGroupActivity_MustHaveActivity {
            get {
                return ResourceManager.GetString("IQVarGroupActivity_MustHaveActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group can only contain Variable Activities.
        /// </summary>
        internal static string IQVarGroupActivity_OnlyIQVariableActivitiesAllowed {
            get {
                return ResourceManager.GetString("IQVarGroupActivity_OnlyIQVariableActivitiesAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable Tab Group.
        /// </summary>
        internal static string IQVarTabGroupActivity_DisplayName {
            get {
                return ResourceManager.GetString("IQVarTabGroupActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the activity in the designer and the name which will be displayed on the tab created in the IQ Preferences Dialog..
        /// </summary>
        internal static string IQVarTabGroupActivity_DisplayName_Description {
            get {
                return ResourceManager.GetString("IQVarTabGroupActivity_DisplayName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must have at least one child activity.
        /// </summary>
        internal static string IQVarTabGroupActivity_MustHaveActivity {
            get {
                return ResourceManager.GetString("IQVarTabGroupActivity_MustHaveActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group can only contain Variable Group Activities.
        /// </summary>
        internal static string IQVarTabGroupActivity_OnlyIQTabVariableActivitiesAllowed {
            get {
                return ResourceManager.GetString("IQVarTabGroupActivity_OnlyIQTabVariableActivitiesAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flowsheet - Tab View.
        /// </summary>
        internal static string IQVarTabViewActivity_DisplayName {
            get {
                return ResourceManager.GetString("IQVarTabViewActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Value.
        /// </summary>
        internal static string MaximumValue_DisplayName {
            get {
                return ResourceManager.GetString("MaximumValue_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit number of characters entered.
        /// </summary>
        internal static string MaxLength_DisplayName {
            get {
                return ResourceManager.GetString("MaxLength_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Value.
        /// </summary>
        internal static string MinimumValue_DisplayName {
            get {
                return ResourceManager.GetString("MinimumValue_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum value is greater than the maximum value.  Please resolve and try again..
        /// </summary>
        internal static string MinValueGreaterThanMax {
            get {
                return ResourceManager.GetString("MinValueGreaterThanMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (No View Selected).
        /// </summary>
        internal static string NoViewSelected {
            get {
                return ResourceManager.GetString("NoViewSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Box.
        /// </summary>
        internal static string ObsDefType_CheckBox {
            get {
                return ResourceManager.GetString("ObsDefType_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Title.
        /// </summary>
        internal static string ObsDefType_Choice {
            get {
                return ResourceManager.GetString("ObsDefType_Choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string ObsDefType_Date {
            get {
                return ResourceManager.GetString("ObsDefType_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string ObsDefType_NoneSelected {
            get {
                return ResourceManager.GetString("ObsDefType_NoneSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric.
        /// </summary>
        internal static string ObsDefType_Numeric {
            get {
                return ResourceManager.GetString("ObsDefType_Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String.
        /// </summary>
        internal static string ObsDefType_String {
            get {
                return ResourceManager.GetString("ObsDefType_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string ObsDefType_Time {
            get {
                return ResourceManager.GetString("ObsDefType_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a drug..
        /// </summary>
        internal static string PleaseEnterADrug {
            get {
                return ResourceManager.GetString("PleaseEnterADrug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practice Management.
        /// </summary>
        internal static string PracticeManagement_Category {
            get {
                return ResourceManager.GetString("PracticeManagement_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predefined value.
        /// </summary>
        internal static string PredefinedValue {
            get {
                return ResourceManager.GetString("PredefinedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be less than {0:Max}.
        /// </summary>
        internal static string RangeErrorAboveMax {
            get {
                return ResourceManager.GetString("RangeErrorAboveMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be greater than {0:Min}.
        /// </summary>
        internal static string RangeErrorBelowMin {
            get {
                return ResourceManager.GetString("RangeErrorBelowMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be between {0:Min} and {1:Max}.
        /// </summary>
        internal static string RangeErrorBetween {
            get {
                return ResourceManager.GetString("RangeErrorBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected value.
        /// </summary>
        internal static string SelectedValue {
            get {
                return ResourceManager.GetString("SelectedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Staff Category.
        /// </summary>
        internal static string SelectStaffCategory {
            get {
                return ResourceManager.GetString("SelectStaffCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Staff Type.
        /// </summary>
        internal static string SelectStaffType {
            get {
                return ResourceManager.GetString("SelectStaffType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Supplies.
        /// </summary>
        internal static string ShowSupplies_DisplayName {
            get {
                return ResourceManager.GetString("ShowSupplies_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to category.
        /// </summary>
        internal static string StaffCategoryLabel {
            get {
                return ResourceManager.GetString("StaffCategoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type.
        /// </summary>
        internal static string StaffTypeLabel {
            get {
                return ResourceManager.GetString("StaffTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains (Case Sensitive).
        /// </summary>
        internal static string StringAlgorithmContains {
            get {
                return ResourceManager.GetString("StringAlgorithmContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains (Case Insensitive).
        /// </summary>
        internal static string StringAlgorithmContainsIgnoreCase {
            get {
                return ResourceManager.GetString("StringAlgorithmContainsIgnoreCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equals (Case Sensitive).
        /// </summary>
        internal static string StringAlgorithmEquals {
            get {
                return ResourceManager.GetString("StringAlgorithmEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equals (Case Insensitive).
        /// </summary>
        internal static string StringAlgorithmEqualsIgnoreCase {
            get {
                return ResourceManager.GetString("StringAlgorithmEqualsIgnoreCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular Expression.
        /// </summary>
        internal static string StringAlgorithmRegEx {
            get {
                return ResourceManager.GetString("StringAlgorithmRegEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upper and Lower Limits.
        /// </summary>
        internal static string StringAlgorithmUpperLowerLimits {
            get {
                return ResourceManager.GetString("StringAlgorithmUpperLowerLimits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates Root.
        /// </summary>
        internal static string TemplatesRoot_DisplayName {
            get {
                return ResourceManager.GetString("TemplatesRoot_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        internal static string True {
            get {
                return ResourceManager.GetString("True", resourceCulture);
            }
        }
    }
}
