//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impac.Mosaiq.IQ.Activities.PM {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Impac.Mosaiq.IQ.Activities.PM.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chk_Id.
        /// </summary>
        internal static string AttachNoteToQclActivity_ChkId_Description {
            get {
                return ResourceManager.GetString("AttachNoteToQclActivity_ChkId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check List ID.
        /// </summary>
        internal static string AttachNoteToQclActivity_ChkId_DisplayName {
            get {
                return ResourceManager.GetString("AttachNoteToQclActivity_ChkId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Note to QCL.
        /// </summary>
        internal static string AttachNoteToQclActivity_DisplayName {
            get {
                return ResourceManager.GetString("AttachNoteToQclActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note_ID.
        /// </summary>
        internal static string AttachNoteToQclActivity_NoteId_Description {
            get {
                return ResourceManager.GetString("AttachNoteToQclActivity_NoteId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note ID.
        /// </summary>
        internal static string AttachNoteToQclActivity_NoteId_DisplayName {
            get {
                return ResourceManager.GetString("AttachNoteToQclActivity_NoteId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The primary key of the QCL to complete..
        /// </summary>
        internal static string CompleteQclActivity_ChkId_Description {
            get {
                return ResourceManager.GetString("CompleteQclActivity_ChkId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chk_Id.
        /// </summary>
        internal static string CompleteQclActivity_ChkId_DisplayName {
            get {
                return ResourceManager.GetString("CompleteQclActivity_ChkId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete QCL.
        /// </summary>
        internal static string CompleteQclActivity_DisplayName {
            get {
                return ResourceManager.GetString("CompleteQclActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The completed (staff/location) value of the QCL.  If no value is provided, the logged in staff member will be used..
        /// </summary>
        internal static string CompleteQclActivity_StaffIdCompleted_Description {
            get {
                return ResourceManager.GetString("CompleteQclActivity_StaffIdCompleted_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string CompleteQclActivity_StaffIdCompleted_DisplayName {
            get {
                return ResourceManager.GetString("CompleteQclActivity_StaffIdCompleted_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Note.
        /// </summary>
        internal static string CreateNoteActivity_DisplayName {
            get {
                return ResourceManager.GetString("CreateNoteActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note .
        /// </summary>
        internal static string CreateNoteActivity_Note_Description {
            get {
                return ResourceManager.GetString("CreateNoteActivity_Note_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string CreateNoteActivity_Note_DisplayName {
            get {
                return ResourceManager.GetString("CreateNoteActivity_Note_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note ID.
        /// </summary>
        internal static string CreateNoteActivity_NoteId_Description {
            get {
                return ResourceManager.GetString("CreateNoteActivity_NoteId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note ID.
        /// </summary>
        internal static string CreateNoteActivity_NoteId_DisplayName {
            get {
                return ResourceManager.GetString("CreateNoteActivity_NoteId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Note.
        /// </summary>
        internal static string CreateNoteActivity_NoteType_Description {
            get {
                return ResourceManager.GetString("CreateNoteActivity_NoteType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note Type.
        /// </summary>
        internal static string CreateNoteActivity_NoteType_DisplayName {
            get {
                return ResourceManager.GetString("CreateNoteActivity_NoteType_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The patient value of the Note..
        /// </summary>
        internal static string CreateNoteActivity_PatId1_Description {
            get {
                return ResourceManager.GetString("CreateNoteActivity_PatId1_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note Subject.
        /// </summary>
        internal static string CreateNoteActivity_Subject_Description {
            get {
                return ResourceManager.GetString("CreateNoteActivity_Subject_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string CreateNoteActivity_Subject_DisplayName {
            get {
                return ResourceManager.GetString("CreateNoteActivity_Subject_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The billable group of the QCL..
        /// </summary>
        internal static string CreateQclActivity_CGroup_Description {
            get {
                return ResourceManager.GetString("CreateQclActivity_CGroup_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billable Code Group.
        /// </summary>
        internal static string CreateQclActivity_CGroup_DisplayName {
            get {
                return ResourceManager.GetString("CreateQclActivity_CGroup_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The primary key value of the QCL..
        /// </summary>
        internal static string CreateQclActivity_ChkId_Description {
            get {
                return ResourceManager.GetString("CreateQclActivity_ChkId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chk_Id.
        /// </summary>
        internal static string CreateQclActivity_ChkId_DisplayName {
            get {
                return ResourceManager.GetString("CreateQclActivity_ChkId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The comment value of the QCL..
        /// </summary>
        internal static string CreateQclActivity_Comment_Description {
            get {
                return ResourceManager.GetString("CreateQclActivity_Comment_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string CreateQclActivity_Comment_DisplayName {
            get {
                return ResourceManager.GetString("CreateQclActivity_Comment_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create QCL.
        /// </summary>
        internal static string CreateQclActivity_DisplayName {
            get {
                return ResourceManager.GetString("CreateQclActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The due date value of the QCL..
        /// </summary>
        internal static string CreateQclActivity_DueDate_Description {
            get {
                return ResourceManager.GetString("CreateQclActivity_DueDate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Date.
        /// </summary>
        internal static string CreateQclActivity_DueDate_DisplayName {
            get {
                return ResourceManager.GetString("CreateQclActivity_DueDate_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The instructions value of the QCL..
        /// </summary>
        internal static string CreateQclActivity_Instructions_Description {
            get {
                return ResourceManager.GetString("CreateQclActivity_Instructions_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions.
        /// </summary>
        internal static string CreateQclActivity_Instructions_DisplayName {
            get {
                return ResourceManager.GetString("CreateQclActivity_Instructions_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The patient value of the QCL..
        /// </summary>
        internal static string CreateQclActivity_PatId1_Description {
            get {
                return ResourceManager.GetString("CreateQclActivity_PatId1_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Prs_Id of the billable code of the QCL..
        /// </summary>
        internal static string CreateQclActivity_PrsId_Description {
            get {
                return ResourceManager.GetString("CreateQclActivity_PrsId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billable Code.
        /// </summary>
        internal static string CreateQclActivity_PrsId_DisplayName {
            get {
                return ResourceManager.GetString("CreateQclActivity_PrsId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requesting (staff/location) value of the QCL..
        /// </summary>
        internal static string CreateQclActivity_StaffIdRequesting_Description {
            get {
                return ResourceManager.GetString("CreateQclActivity_StaffIdRequesting_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requesting.
        /// </summary>
        internal static string CreateQclActivity_StaffIdRequesting_DisplayName {
            get {
                return ResourceManager.GetString("CreateQclActivity_StaffIdRequesting_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The responsible (staff/location) value of the QCL..
        /// </summary>
        internal static string CreateQclActivity_StaffIdResponsible_Description {
            get {
                return ResourceManager.GetString("CreateQclActivity_StaffIdResponsible_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsible.
        /// </summary>
        internal static string CreateQclActivity_StaffIdResponsible_DisplayName {
            get {
                return ResourceManager.GetString("CreateQclActivity_StaffIdResponsible_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Tsk_Id of the QCL task..
        /// </summary>
        internal static string CreateQclActivity_TskId_Description {
            get {
                return ResourceManager.GetString("CreateQclActivity_TskId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        internal static string CreateQclActivity_TskId_DisplayName {
            get {
                return ResourceManager.GetString("CreateQclActivity_TskId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create QCL (Show Form).
        /// </summary>
        internal static string CreateQclWithFormActivity_DisplayName {
            get {
                return ResourceManager.GetString("CreateQclWithFormActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Pro_Id of the procedure that will be pre-populated when the QCL form opens .
        /// </summary>
        internal static string CreateQclWithFormActivity_ProId_Description {
            get {
                return ResourceManager.GetString("CreateQclWithFormActivity_ProId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Staff_Id of the responsible staff/location that will be pre-populated when the QCL form opens.
        /// </summary>
        internal static string CreateQclWithFormActivity_StaffIdResponsible_Description {
            get {
                return ResourceManager.GetString("CreateQclWithFormActivity_StaffIdResponsible_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The primary key of the QCL..
        /// </summary>
        internal static string DeleteQclActivity_ChkId_Description {
            get {
                return ResourceManager.GetString("DeleteQclActivity_ChkId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chk_Id.
        /// </summary>
        internal static string DeleteQclActivity_ChkId_DisplayName {
            get {
                return ResourceManager.GetString("DeleteQclActivity_ChkId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete QCL .
        /// </summary>
        internal static string DeleteQclActivity_DisplayName {
            get {
                return ResourceManager.GetString("DeleteQclActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demographics.
        /// </summary>
        internal static string Demographics_Category {
            get {
                return ResourceManager.GetString("Demographics_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string Department_DisplayName {
            get {
                return ResourceManager.GetString("Department_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attending MD for the patient and department provided..
        /// </summary>
        internal static string GetAttendingMdActivity_AttendingMdId_Description {
            get {
                return ResourceManager.GetString("GetAttendingMdActivity_AttendingMdId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attending MD.
        /// </summary>
        internal static string GetAttendingMdActivity_AttendingMdId_DisplayName {
            get {
                return ResourceManager.GetString("GetAttendingMdActivity_AttendingMdId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Attending MD.
        /// </summary>
        internal static string GetAttendingMdActivity_DisplayName {
            get {
                return ResourceManager.GetString("GetAttendingMdActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the department for which the attending MD will be retrieved..
        /// </summary>
        internal static string GetAttendingMdActivity_InstId_Description {
            get {
                return ResourceManager.GetString("GetAttendingMdActivity_InstId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the patient whose attending MD will be retrieved..
        /// </summary>
        internal static string GetAttendingMdActivity_PatId1_Description {
            get {
                return ResourceManager.GetString("GetAttendingMdActivity_PatId1_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Next Clinic Day.
        /// </summary>
        internal static string GetNextClinicDay_DisplayName {
            get {
                return ResourceManager.GetString("GetNextClinicDay_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets the next day that the clinic will be open after the start date provided (or Today if no date is provided).
        /// </summary>
        internal static string GetNextClinicDayActivity_NextClinicDate_Description {
            get {
                return ResourceManager.GetString("GetNextClinicDayActivity_NextClinicDate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Clinic Day.
        /// </summary>
        internal static string GetNextClinicDayActivity_NextClinicDate_DisplayName {
            get {
                return ResourceManager.GetString("GetNextClinicDayActivity_NextClinicDate_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a clinic day within the next 30 days.
        /// </summary>
        internal static string GetNextClinicDayActivity_NextClinicDayNotFound {
            get {
                return ResourceManager.GetString("GetNextClinicDayActivity_NextClinicDayNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date from which to begin searching for clinic days.  The current date will be used if no value is provided..
        /// </summary>
        internal static string GetNextClinicDayActivity_SearchStartDate_Description {
            get {
                return ResourceManager.GetString("GetNextClinicDayActivity_SearchStartDate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Start Date.
        /// </summary>
        internal static string GetNextClinicDayActivity_SearchStartDate_DisplayName {
            get {
                return ResourceManager.GetString("GetNextClinicDayActivity_SearchStartDate_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string Notes_Category {
            get {
                return ResourceManager.GetString("Notes_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        internal static string ParseScheduleDataActivity_Activity_Description {
            get {
                return ResourceManager.GetString("ParseScheduleDataActivity_Activity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        internal static string ParseScheduleDataActivity_Activity_DisplayName {
            get {
                return ResourceManager.GetString("ParseScheduleDataActivity_Activity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment Date and Time.
        /// </summary>
        internal static string ParseScheduleDataActivity_AppDtTm_Description {
            get {
                return ResourceManager.GetString("ParseScheduleDataActivity_AppDtTm_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment Date and Time.
        /// </summary>
        internal static string ParseScheduleDataActivity_AppDtTm_DisplayName {
            get {
                return ResourceManager.GetString("ParseScheduleDataActivity_AppDtTm_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Date and Time.
        /// </summary>
        internal static string ParseScheduleDataActivity_CreateDtTm_Description {
            get {
                return ResourceManager.GetString("ParseScheduleDataActivity_CreateDtTm_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Date and Time.
        /// </summary>
        internal static string ParseScheduleDataActivity_CreateDtTm_DisplayName {
            get {
                return ResourceManager.GetString("ParseScheduleDataActivity_CreateDtTm_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create ID.
        /// </summary>
        internal static string ParseScheduleDataActivity_CreateId_Description {
            get {
                return ResourceManager.GetString("ParseScheduleDataActivity_CreateId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create ID.
        /// </summary>
        internal static string ParseScheduleDataActivity_CreateId_DisplayName {
            get {
                return ResourceManager.GetString("ParseScheduleDataActivity_CreateId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parse Schedule Data.
        /// </summary>
        internal static string ParseScheduleDataActivity_DisplayName {
            get {
                return ResourceManager.GetString("ParseScheduleDataActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient ID.
        /// </summary>
        internal static string ParseScheduleDataActivity_PatId1_Description {
            get {
                return ResourceManager.GetString("ParseScheduleDataActivity_PatId1_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient ID.
        /// </summary>
        internal static string ParseScheduleDataActivity_PatId1_DisplayName {
            get {
                return ResourceManager.GetString("ParseScheduleDataActivity_PatId1_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        internal static string ParseScheduleDataActivity_Private_Description {
            get {
                return ResourceManager.GetString("ParseScheduleDataActivity_Private_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        internal static string ParseScheduleDataActivity_Private_DisplayName {
            get {
                return ResourceManager.GetString("ParseScheduleDataActivity_Private_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Data.
        /// </summary>
        internal static string ParseScheduleDataActivity_ScheduleData_Description {
            get {
                return ResourceManager.GetString("ParseScheduleDataActivity_ScheduleData_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Data.
        /// </summary>
        internal static string ParseScheduleDataActivity_ScheduleData_DisplayName {
            get {
                return ResourceManager.GetString("ParseScheduleDataActivity_ScheduleData_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff ID.
        /// </summary>
        internal static string ParseScheduleDataActivity_StaffId_Description {
            get {
                return ResourceManager.GetString("ParseScheduleDataActivity_StaffId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff ID.
        /// </summary>
        internal static string ParseScheduleDataActivity_StaffId_DisplayName {
            get {
                return ResourceManager.GetString("ParseScheduleDataActivity_StaffId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        internal static string Patient_DisplayName {
            get {
                return ResourceManager.GetString("Patient_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practice Management.
        /// </summary>
        internal static string PracticeManagement_ActivityGroup {
            get {
                return ResourceManager.GetString("PracticeManagement_ActivityGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The completed state of the QCL.  A null or empty value matches QCL&apos;s regardless of whether they are completed..
        /// </summary>
        internal static string QclExistsActivity_Completed_Description {
            get {
                return ResourceManager.GetString("QclExistsActivity_Completed_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string QclExistsActivity_Completed_DisplayName {
            get {
                return ResourceManager.GetString("QclExistsActivity_Completed_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QCL Exists.
        /// </summary>
        internal static string QclExistsActivity_DisplayName {
            get {
                return ResourceManager.GetString("QclExistsActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns whether a QCL with matching attributes exists..
        /// </summary>
        internal static string QclExistsActivity_QclExists_Description {
            get {
                return ResourceManager.GetString("QclExistsActivity_QclExists_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exists.
        /// </summary>
        internal static string QclExistsActivity_QclExists_DisplayName {
            get {
                return ResourceManager.GetString("QclExistsActivity_QclExists_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality Check List.
        /// </summary>
        internal static string QualityChecklist_Category {
            get {
                return ResourceManager.GetString("QualityChecklist_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduling.
        /// </summary>
        internal static string Scheduling_Category {
            get {
                return ResourceManager.GetString("Scheduling_Category", resourceCulture);
            }
        }
    }
}
