//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impac.Mosaiq.IQ.Activities.RadOnc {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Impac.Mosaiq.IQ.Activities.RadOnc.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount of fractions to add (+) or subtract (-) from the number of fractions in the given Site. The total dose is also adjusted accordingly. The fraction dose remains unchanged.
        /// </summary>
        internal static string ChangePrescribedFractionsActivity_DeltaFraction_Description {
            get {
                return ResourceManager.GetString("ChangePrescribedFractionsActivity_DeltaFraction_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delta Fractions.
        /// </summary>
        internal static string ChangePrescribedFractionsActivity_DeltaFraction_DisplayName {
            get {
                return ResourceManager.GetString("ChangePrescribedFractionsActivity_DeltaFraction_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Treatment Fractions.
        /// </summary>
        internal static string ChangePrescribedFractionsActivity_DisplayName {
            get {
                return ResourceManager.GetString("ChangePrescribedFractionsActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns True if the number of fractions was changed for given Rad Rx, False otherwise.
        /// </summary>
        internal static string ChangePrescribedFractionsActivity_FractionsChanged_Description {
            get {
                return ResourceManager.GetString("ChangePrescribedFractionsActivity_FractionsChanged_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fractions Changed.
        /// </summary>
        internal static string ChangePrescribedFractionsActivity_FractionsChanged_DisplayName {
            get {
                return ResourceManager.GetString("ChangePrescribedFractionsActivity_FractionsChanged_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient (_patId1) for which to change the number of fractios for.
        /// </summary>
        internal static string ChangePrescribedFractionsActivity_PatId_Description {
            get {
                return ResourceManager.GetString("ChangePrescribedFractionsActivity_PatId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        internal static string ChangePrescribedFractionsActivity_PatId_DisplayName {
            get {
                return ResourceManager.GetString("ChangePrescribedFractionsActivity_PatId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The persistence manager to use with the query. If not provided, a new persistence manager will be created..
        /// </summary>
        internal static string ChangePrescribedFractionsActivity_PersistenceManager_Description {
            get {
                return ResourceManager.GetString("ChangePrescribedFractionsActivity_PersistenceManager_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistence Manager.
        /// </summary>
        internal static string ChangePrescribedFractionsActivity_PersistenceManager_DisplayName {
            get {
                return ResourceManager.GetString("ChangePrescribedFractionsActivity_PersistenceManager_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The unique ID (Sit_Id) of the Rad Rx to adjust prescription for.
        /// </summary>
        internal static string ChangePrescribedFractionsActivity_SIT_ID_Description {
            get {
                return ResourceManager.GetString("ChangePrescribedFractionsActivity_SIT_ID_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        internal static string ChangePrescribedFractionsActivity_SIT_ID_DisplayName {
            get {
                return ResourceManager.GetString("ChangePrescribedFractionsActivity_SIT_ID_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Secondary Dose Site.
        /// </summary>
        internal static string CreateSecondaryDoseSiteActivity_DisplayName {
            get {
                return ResourceManager.GetString("CreateSecondaryDoseSiteActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dose coefficient for all treatment fields part of this Secondary Dose Site (default = 1.000). The coefficient must be between 0.0000 and 9.9999. The Dose Site will not be created if the coefficient is outside this range..
        /// </summary>
        internal static string CreateSecondaryDoseSiteActivity_DoseCoeff_Description {
            get {
                return ResourceManager.GetString("CreateSecondaryDoseSiteActivity_DoseCoeff_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dose Coefficient.
        /// </summary>
        internal static string CreateSecondaryDoseSiteActivity_DoseCoeff_DisplayName {
            get {
                return ResourceManager.GetString("CreateSecondaryDoseSiteActivity_DoseCoeff_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns True if a Secondary Dose Site was created successfully, False otherwise.
        /// </summary>
        internal static string CreateSecondaryDoseSiteActivity_DoseSiteCreated_Description {
            get {
                return ResourceManager.GetString("CreateSecondaryDoseSiteActivity_DoseSiteCreated_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dose Site Created.
        /// </summary>
        internal static string CreateSecondaryDoseSiteActivity_DoseSiteCreated_DisplayName {
            get {
                return ResourceManager.GetString("CreateSecondaryDoseSiteActivity_DoseSiteCreated_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient (_patId1) to create the Secondary Dose Tracking Site for.
        /// </summary>
        internal static string CreateSecondaryDoseSiteActivity_PatId_Description {
            get {
                return ResourceManager.GetString("CreateSecondaryDoseSiteActivity_PatId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        internal static string CreateSecondaryDoseSiteActivity_PatId_DisplayName {
            get {
                return ResourceManager.GetString("CreateSecondaryDoseSiteActivity_PatId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The persistence manager to use with the query. If not provided, a new persistence manager will be created..
        /// </summary>
        internal static string CreateSecondaryDoseSiteActivity_PersistenceManager_Description {
            get {
                return ResourceManager.GetString("CreateSecondaryDoseSiteActivity_PersistenceManager_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistence Manager.
        /// </summary>
        internal static string CreateSecondaryDoseSiteActivity_PersistenceManager_DisplayName {
            get {
                return ResourceManager.GetString("CreateSecondaryDoseSiteActivity_PersistenceManager_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name for the Secondary Dose Site to create. This name must be unique. If it already exists the Secondary Dose Site will not be created. If the name exists of more then 20 characters, it will be truncated to 20..
        /// </summary>
        internal static string CreateSecondaryDoseSiteActivity_RegionName_Description {
            get {
                return ResourceManager.GetString("CreateSecondaryDoseSiteActivity_RegionName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region Name.
        /// </summary>
        internal static string CreateSecondaryDoseSiteActivity_RegionName_DisplayName {
            get {
                return ResourceManager.GetString("CreateSecondaryDoseSiteActivity_RegionName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Rx Sites that will contribute to the newly created Secondary Dose Site.
        /// </summary>
        internal static string CreateSecondaryDoseSiteActivity_RxSite_Description {
            get {
                return ResourceManager.GetString("CreateSecondaryDoseSiteActivity_RxSite_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sites.
        /// </summary>
        internal static string CreateSecondaryDoseSiteActivity_RxSite_DisplayName {
            get {
                return ResourceManager.GetString("CreateSecondaryDoseSiteActivity_RxSite_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Treatment Fields from Calendar Session.
        /// </summary>
        internal static string DeleteFieldsFromSessionActivity_DisplayName {
            get {
                return ResourceManager.GetString("DeleteFieldsFromSessionActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the number of records (treatment fields) deleted from the Calendar. Set to -1 if delete failed..
        /// </summary>
        internal static string DeleteFieldsFromSessionActivity_FieldsDeleted_Description {
            get {
                return ResourceManager.GetString("DeleteFieldsFromSessionActivity_FieldsDeleted_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treatment Fields Deleted.
        /// </summary>
        internal static string DeleteFieldsFromSessionActivity_FieldsDeleted_DisplayName {
            get {
                return ResourceManager.GetString("DeleteFieldsFromSessionActivity_FieldsDeleted_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient (_patId1) for which to delete Treatment Fields from Session.
        /// </summary>
        internal static string DeleteFieldsFromSessionActivity_PatId_Description {
            get {
                return ResourceManager.GetString("DeleteFieldsFromSessionActivity_PatId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        internal static string DeleteFieldsFromSessionActivity_PatId_DisplayName {
            get {
                return ResourceManager.GetString("DeleteFieldsFromSessionActivity_PatId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The unique ID (Pci_Id) of the treatment session to remove fields of.
        /// </summary>
        internal static string DeleteFieldsFromSessionActivity_PCI_ID_Description {
            get {
                return ResourceManager.GetString("DeleteFieldsFromSessionActivity_PCI_ID_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar Session.
        /// </summary>
        internal static string DeleteFieldsFromSessionActivity_PCI_ID_DisplayName {
            get {
                return ResourceManager.GetString("DeleteFieldsFromSessionActivity_PCI_ID_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The persistence manager to use with the query. If not provided, a new persistence manager will be created..
        /// </summary>
        internal static string DeleteFieldsFromSessionActivity_PersistenceManager_Description {
            get {
                return ResourceManager.GetString("DeleteFieldsFromSessionActivity_PersistenceManager_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistence Manager.
        /// </summary>
        internal static string DeleteFieldsFromSessionActivity_PersistenceManager_DisplayName {
            get {
                return ResourceManager.GetString("DeleteFieldsFromSessionActivity_PersistenceManager_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dose Tracking Site.
        /// </summary>
        internal static string DoseTrackingSite_Category {
            get {
                return ResourceManager.GetString("DoseTrackingSite_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Treatment Fields in to Calendar Session.
        /// </summary>
        internal static string InsertFieldsIntoSessionActivity_DisplayName {
            get {
                return ResourceManager.GetString("InsertFieldsIntoSessionActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the number of records (treatment fields) inserted in to the Calendar. Set to -1 if insert has failed..
        /// </summary>
        internal static string InsertFieldsIntoSessionActivity_FieldsInserted_Description {
            get {
                return ResourceManager.GetString("InsertFieldsIntoSessionActivity_FieldsInserted_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treatment Fields Inserted.
        /// </summary>
        internal static string InsertFieldsIntoSessionActivity_FieldsInserted_DisplayName {
            get {
                return ResourceManager.GetString("InsertFieldsIntoSessionActivity_FieldsInserted_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient (_patId1) for which to insert Treatment Fields in to the Session.
        /// </summary>
        internal static string InsertFieldsIntoSessionActivity_PatId_Description {
            get {
                return ResourceManager.GetString("InsertFieldsIntoSessionActivity_PatId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        internal static string InsertFieldsIntoSessionActivity_PatId_DisplayName {
            get {
                return ResourceManager.GetString("InsertFieldsIntoSessionActivity_PatId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The unique ID (Pci_Id) of the treatment session to insert fields for.
        /// </summary>
        internal static string InsertFieldsIntoSessionActivity_PCI_ID_Description {
            get {
                return ResourceManager.GetString("InsertFieldsIntoSessionActivity_PCI_ID_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar Session.
        /// </summary>
        internal static string InsertFieldsIntoSessionActivity_PCI_ID_DisplayName {
            get {
                return ResourceManager.GetString("InsertFieldsIntoSessionActivity_PCI_ID_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The persistence manager to use with the query. If not provided, a new persistence manager will be created..
        /// </summary>
        internal static string InsertFieldsIntoSessionActivity_PersistenceManager_Description {
            get {
                return ResourceManager.GetString("InsertFieldsIntoSessionActivity_PersistenceManager_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistence Manager.
        /// </summary>
        internal static string InsertFieldsIntoSessionActivity_PersistenceManager_DisplayName {
            get {
                return ResourceManager.GetString("InsertFieldsIntoSessionActivity_PersistenceManager_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The unique ID (Sit_Id) of the Rx Site to adjust the prescription of.
        /// </summary>
        internal static string InsertFieldsIntoSessionActivity_SIT_ID_Description {
            get {
                return ResourceManager.GetString("InsertFieldsIntoSessionActivity_SIT_ID_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        internal static string InsertFieldsIntoSessionActivity_SIT_ID_DisplayName {
            get {
                return ResourceManager.GetString("InsertFieldsIntoSessionActivity_SIT_ID_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status for the inserted fields: 5 = Approved, 7 = Pending (default = 5 (Approved)).
        /// </summary>
        internal static string InsertFieldsIntoSessionActivity_StatusEnum_Description {
            get {
                return ResourceManager.GetString("InsertFieldsIntoSessionActivity_StatusEnum_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Status.
        /// </summary>
        internal static string InsertFieldsIntoSessionActivity_StatusEnum_DisplayName {
            get {
                return ResourceManager.GetString("InsertFieldsIntoSessionActivity_StatusEnum_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use AFS (Automatic Field Sequencing) to deliver the beam sequence. Default is False. If both AFS and MFS are set to true, no fields will be inserted!.
        /// </summary>
        internal static string InsertFieldsIntoSessionActivity_UseAFS_Description {
            get {
                return ResourceManager.GetString("InsertFieldsIntoSessionActivity_UseAFS_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use AFS.
        /// </summary>
        internal static string InsertFieldsIntoSessionActivity_UseAFS_DisplayName {
            get {
                return ResourceManager.GetString("InsertFieldsIntoSessionActivity_UseAFS_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use MFS (Manual Field Sequencing)  to deliver the beam sequence. Default is False. If both AFS and MFS are set to true, no fields will be inserted! .
        /// </summary>
        internal static string InsertFieldsIntoSessionActivity_UseMFS_Description {
            get {
                return ResourceManager.GetString("InsertFieldsIntoSessionActivity_UseMFS_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use MFS.
        /// </summary>
        internal static string InsertFieldsIntoSessionActivity_UseMFS_DisplayName {
            get {
                return ResourceManager.GetString("InsertFieldsIntoSessionActivity_UseMFS_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radiation Oncology.
        /// </summary>
        internal static string RadOnc_ActivityGroup {
            get {
                return ResourceManager.GetString("RadOnc_ActivityGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treatment Calendar.
        /// </summary>
        internal static string TreatmentCalendar_Category {
            get {
                return ResourceManager.GetString("TreatmentCalendar_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treatment Prescription.
        /// </summary>
        internal static string TreatmentPrescription_Category {
            get {
                return ResourceManager.GetString("TreatmentPrescription_Category", resourceCulture);
            }
        }
    }
}
