//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impac.Mosaiq.IQ.Activities.Queries {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Impac.Mosaiq.IQ.Activities.Queries.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config.
        /// </summary>
        internal static string Configuration_Category {
            get {
                return ResourceManager.GetString("Configuration_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treatment Calendar Items by Pci_Id.
        /// </summary>
        internal static string FindCalendarItemsByPciIdActivity_DisplayName {
            get {
                return ResourceManager.GetString("FindCalendarItemsByPciIdActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Patient ID (_patId1) for which to return the Calendar Items..
        /// </summary>
        internal static string FindCalendarItemsByPciIdActivity_PatId_Description {
            get {
                return ResourceManager.GetString("FindCalendarItemsByPciIdActivity_PatId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        internal static string FindCalendarItemsByPciIdActivity_PatId_DisplayName {
            get {
                return ResourceManager.GetString("FindCalendarItemsByPciIdActivity_PatId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The primary ID (Pci_Id) of the Calendar Session for which to return scheduled field object from the database.
        /// </summary>
        internal static string FindCalendarItemsByPciIdActivity_PciId_Description {
            get {
                return ResourceManager.GetString("FindCalendarItemsByPciIdActivity_PciId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter Session.
        /// </summary>
        internal static string FindCalendarItemsByPciIdActivity_PciId_DisplayName {
            get {
                return ResourceManager.GetString("FindCalendarItemsByPciIdActivity_PciId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar Sessions by Pcp_Id.
        /// </summary>
        internal static string FindCalendarSessionsByPcpIdActivity_DisplayName {
            get {
                return ResourceManager.GetString("FindCalendarSessionsByPcpIdActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If supplied, returns only the sessions that are scheduled before this given date (Due_DtTm).
        /// </summary>
        internal static string FindCalendarSessionsByPcpIdActivity_EndDate_Description {
            get {
                return ResourceManager.GetString("FindCalendarSessionsByPcpIdActivity_EndDate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        internal static string FindCalendarSessionsByPcpIdActivity_EndDate_DisplayName {
            get {
                return ResourceManager.GetString("FindCalendarSessionsByPcpIdActivity_EndDate_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The patient ID (_patId1) for which to return Calender
        ///       Sessions..
        /// </summary>
        internal static string FindCalendarSessionsByPcpIdActivity_PatId_Description {
            get {
                return ResourceManager.GetString("FindCalendarSessionsByPcpIdActivity_PatId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        internal static string FindCalendarSessionsByPcpIdActivity_PatId_DisplayName {
            get {
                return ResourceManager.GetString("FindCalendarSessionsByPcpIdActivity_PatId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The primary key of the Course (Care Plan) for which to return
        ///       Calendar Session object from the database
        ///    .
        /// </summary>
        internal static string FindCalendarSessionsByPcpIdActivity_PcpId_Description {
            get {
                return ResourceManager.GetString("FindCalendarSessionsByPcpIdActivity_PcpId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Careplan (Course).
        /// </summary>
        internal static string FindCalendarSessionsByPcpIdActivity_PcpId_DisplayName {
            get {
                return ResourceManager.GetString("FindCalendarSessionsByPcpIdActivity_PcpId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If supplied, returns only the sessions that are scheduled after this given date (Due_DtTm).
        /// </summary>
        internal static string FindCalendarSessionsByPcpIdActivity_StartDate_Description {
            get {
                return ResourceManager.GetString("FindCalendarSessionsByPcpIdActivity_StartDate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string FindCalendarSessionsByPcpIdActivity_StartDate_DisplayName {
            get {
                return ResourceManager.GetString("FindCalendarSessionsByPcpIdActivity_StartDate_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters out the results which do not contain the value of this CommentFieldString (case insensitive, regular expressions are handled as normal characters) in the comment field of the Course for the given Patient. When string is null the comment field is completely ignored, but when the string has an empty value (&quot;&quot;) it filters out all the non empty field. The ProtocolFieldString and LogicalOperator parameter are also part of the filter process..
        /// </summary>
        internal static string FindCoursesByCommentOrProtocolActivity_CommentFieldString_Description {
            get {
                return ResourceManager.GetString("FindCoursesByCommentOrProtocolActivity_CommentFieldString_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment String.
        /// </summary>
        internal static string FindCoursesByCommentOrProtocolActivity_CommentFieldString_DisplayName {
            get {
                return ResourceManager.GetString("FindCoursesByCommentOrProtocolActivity_CommentFieldString_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courses by Comment or Protocol.
        /// </summary>
        internal static string FindCoursesByCommentOrProtocolActivity_DisplayName {
            get {
                return ResourceManager.GetString("FindCoursesByCommentOrProtocolActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logical operator on how to combine the CommentFieldString and ProtocolFieldString in the search query (only AND and OR). When one of those search strings is null the operator is ignored and the search query is only applied to the non null string..
        /// </summary>
        internal static string FindCoursesByCommentOrProtocolActivity_LogicalOperator_Description {
            get {
                return ResourceManager.GetString("FindCoursesByCommentOrProtocolActivity_LogicalOperator_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logical Operator.
        /// </summary>
        internal static string FindCoursesByCommentOrProtocolActivity_LogicalOperator_DisplayName {
            get {
                return ResourceManager.GetString("FindCoursesByCommentOrProtocolActivity_LogicalOperator_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The patient ID (_patId1) for which to retrieve the Course
        ///       records.
        /// </summary>
        internal static string FindCoursesByCommentOrProtocolActivity_PatId1_Description {
            get {
                return ResourceManager.GetString("FindCoursesByCommentOrProtocolActivity_PatId1_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        internal static string FindCoursesByCommentOrProtocolActivity_PatId1_DisplayName {
            get {
                return ResourceManager.GetString("FindCoursesByCommentOrProtocolActivity_PatId1_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters out the results which do not contain the value of this ProtocolFieldString (case insensitive, regular expressions are handled as normal characters) in the protocol field of the Course for the given Patient. When string is null the protocol field is completely ignored, but when the string has an empty value it filters out all the non empty values of the protocol field. The CommentFieldString and LogicalOperator parameter are also part of the filter process..
        /// </summary>
        internal static string FindCoursesByCommentOrProtocolActivity_ProtocolFieldString_Description {
            get {
                return ResourceManager.GetString("FindCoursesByCommentOrProtocolActivity_ProtocolFieldString_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol String.
        /// </summary>
        internal static string FindCoursesByCommentOrProtocolActivity_ProtocolFieldString_DisplayName {
            get {
                return ResourceManager.GetString("FindCoursesByCommentOrProtocolActivity_ProtocolFieldString_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Configuration by Inst_Id.
        /// </summary>
        internal static string FindDepartmentConfigurationActivity_DisplayName {
            get {
                return ResourceManager.GetString("FindDepartmentConfigurationActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify Institute ID (Inst_Id) of the department.
        /// </summary>
        internal static string FindDepartmentConfigurationActivity_InstId_Description {
            get {
                return ResourceManager.GetString("FindDepartmentConfigurationActivity_InstId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string FindDepartmentConfigurationActivity_InstId_DisplayName {
            get {
                return ResourceManager.GetString("FindDepartmentConfigurationActivity_InstId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dose History by Pat_Id1.
        /// </summary>
        internal static string FindDoseHistoryByPatId1Activity_DisplayName {
            get {
                return ResourceManager.GetString("FindDoseHistoryByPatId1Activity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters out the results after this date and time based on the Tx_DtTm field..
        /// </summary>
        internal static string FindDoseHistoryByPatId1Activity_EndDate_Description {
            get {
                return ResourceManager.GetString("FindDoseHistoryByPatId1Activity_EndDate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        internal static string FindDoseHistoryByPatId1Activity_EndDate_DisplayName {
            get {
                return ResourceManager.GetString("FindDoseHistoryByPatId1Activity_EndDate_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The patient ID (_patId1) for which to retrieve Dose History records.
        /// </summary>
        internal static string FindDoseHistoryByPatId1Activity_PatId_Description {
            get {
                return ResourceManager.GetString("FindDoseHistoryByPatId1Activity_PatId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        internal static string FindDoseHistoryByPatId1Activity_PatId_DisplayName {
            get {
                return ResourceManager.GetString("FindDoseHistoryByPatId1Activity_PatId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Rx Site ID (Sit_Id) for which to retrieve Dose History records (optional).
        /// </summary>
        internal static string FindDoseHistoryByPatId1Activity_SIT_ID_Description {
            get {
                return ResourceManager.GetString("FindDoseHistoryByPatId1Activity_SIT_ID_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        internal static string FindDoseHistoryByPatId1Activity_SIT_ID_DisplayName {
            get {
                return ResourceManager.GetString("FindDoseHistoryByPatId1Activity_SIT_ID_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters out the results before this date and time based on the Tx_DtTm field..
        /// </summary>
        internal static string FindDoseHistoryByPatId1Activity_StartDate_Description {
            get {
                return ResourceManager.GetString("FindDoseHistoryByPatId1Activity_StartDate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string FindDoseHistoryByPatId1Activity_StartDate_DisplayName {
            get {
                return ResourceManager.GetString("FindDoseHistoryByPatId1Activity_StartDate_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dose Site Coefficients by Reg_Id.
        /// </summary>
        internal static string FindDoseSiteCoefficientByRegIdActivity_DisplayName {
            get {
                return ResourceManager.GetString("FindDoseSiteCoefficientByRegIdActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The patient ID (_patId1) for which to retrieve Dose Site Coefficient records.
        /// </summary>
        internal static string FindDoseSiteCoefficientByRegIdActivity_PatId1_Description {
            get {
                return ResourceManager.GetString("FindDoseSiteCoefficientByRegIdActivity_PatId1_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        internal static string FindDoseSiteCoefficientByRegIdActivity_PatId1_DisplayName {
            get {
                return ResourceManager.GetString("FindDoseSiteCoefficientByRegIdActivity_PatId1_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Region ID (Reg_Id) for which to retrieve Dose Site Coefficient records.
        /// </summary>
        internal static string FindDoseSiteCoefficientByRegIdActivity_RegId_Description {
            get {
                return ResourceManager.GetString("FindDoseSiteCoefficientByRegIdActivity_RegId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        internal static string FindDoseSiteCoefficientByRegIdActivity_RegId_DisplayName {
            get {
                return ResourceManager.GetString("FindDoseSiteCoefficientByRegIdActivity_RegId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dose Tracking Sites by Pat_Id1.
        /// </summary>
        internal static string FindDoseTrackingSitesByPatId1Activity_DisplayName {
            get {
                return ResourceManager.GetString("FindDoseTrackingSitesByPatId1Activity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The patient ID (Pat_Id1) for which to retrieve dose tracking site objects.
        /// </summary>
        internal static string FindDoseTrackingSitesByPatId1Activity_PatId1_Description {
            get {
                return ResourceManager.GetString("FindDoseTrackingSitesByPatId1Activity_PatId1_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        internal static string FindDoseTrackingSitesByPatId1Activity_PatId1_DisplayName {
            get {
                return ResourceManager.GetString("FindDoseTrackingSitesByPatId1Activity_PatId1_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If true, only primary dose tracking site objects will be returned.
        /// </summary>
        internal static string FindDoseTrackingSitesByPatId1Activity_PrimaryDoseSitesOnly_Description {
            get {
                return ResourceManager.GetString("FindDoseTrackingSitesByPatId1Activity_PrimaryDoseSitesOnly_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Dose Sites Only.
        /// </summary>
        internal static string FindDoseTrackingSitesByPatId1Activity_PrimaryDoseSitesOnly_DisplayName {
            get {
                return ResourceManager.GetString("FindDoseTrackingSitesByPatId1Activity_PrimaryDoseSitesOnly_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If true, only secondary dose tracking site objects will be returned.
        /// </summary>
        internal static string FindDoseTrackingSitesByPatId1Activity_SecondaryDoseSitesOnly_Description {
            get {
                return ResourceManager.GetString("FindDoseTrackingSitesByPatId1Activity_SecondaryDoseSitesOnly_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary Dose Sites Only.
        /// </summary>
        internal static string FindDoseTrackingSitesByPatId1Activity_SecondaryDoseSitesOnly_DisplayName {
            get {
                return ResourceManager.GetString("FindDoseTrackingSitesByPatId1Activity_SecondaryDoseSitesOnly_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Site ID (Sit_Id) for which to return the dose tracking site object.
        /// </summary>
        internal static string FindDoseTrackingSitesByPatId1Activity_SitId_Description {
            get {
                return ResourceManager.GetString("FindDoseTrackingSitesByPatId1Activity_SitId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        internal static string FindDoseTrackingSitesByPatId1Activity_SitId_DisplayName {
            get {
                return ResourceManager.GetString("FindDoseTrackingSitesByPatId1Activity_SitId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient by Pat_Id1.
        /// </summary>
        internal static string FindPatientByPatId1Activity_DisplayName {
            get {
                return ResourceManager.GetString("FindPatientByPatId1Activity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The primary key of the patient object to return from the database..
        /// </summary>
        internal static string FindPatientByPatId1Activity_PatId1_Description {
            get {
                return ResourceManager.GetString("FindPatientByPatId1Activity_PatId1_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        internal static string FindPatientByPatId1Activity_PatId1_DisplayName {
            get {
                return ResourceManager.GetString("FindPatientByPatId1Activity_PatId1_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rx Site by Sit_Id.
        /// </summary>
        internal static string FindRxSiteBySitIdActivity_DisplayName {
            get {
                return ResourceManager.GetString("FindRxSiteBySitIdActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The primary key of the Rx Site object to return from the database.
        /// </summary>
        internal static string FindRxSiteBySitIdActivity_SitId_Description {
            get {
                return ResourceManager.GetString("FindRxSiteBySitIdActivity_SitId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        internal static string FindRxSiteBySitIdActivity_SitId_DisplayName {
            get {
                return ResourceManager.GetString("FindRxSiteBySitIdActivity_SitId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The substring (case insensitive) to search for in the comment field of the Rx Site for the given patient..
        /// </summary>
        internal static string FindRxSitesByCommentOrPatternActivity_CommentFieldString_Description {
            get {
                return ResourceManager.GetString("FindRxSitesByCommentOrPatternActivity_CommentFieldString_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment String.
        /// </summary>
        internal static string FindRxSitesByCommentOrPatternActivity_CommentFieldString_DisplayName {
            get {
                return ResourceManager.GetString("FindRxSitesByCommentOrPatternActivity_CommentFieldString_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rx Sites by Comment or Pattern.
        /// </summary>
        internal static string FindRxSitesByCommentOrPatternActivity_DisplayName {
            get {
                return ResourceManager.GetString("FindRxSitesByCommentOrPatternActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select one of the operators to combine the selection of Comment and Protocol (default is EntityBooleanOp.Or).
        /// </summary>
        internal static string FindRxSitesByCommentOrPatternActivity_LogicalOperator_Description {
            get {
                return ResourceManager.GetString("FindRxSitesByCommentOrPatternActivity_LogicalOperator_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logical Operator.
        /// </summary>
        internal static string FindRxSitesByCommentOrPatternActivity_LogicalOperator_DisplayName {
            get {
                return ResourceManager.GetString("FindRxSitesByCommentOrPatternActivity_LogicalOperator_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The patient ID (_patId1) for which to retrieve Rx Site records.
        /// </summary>
        internal static string FindRxSitesByCommentOrPatternActivity_PatId1_Description {
            get {
                return ResourceManager.GetString("FindRxSitesByCommentOrPatternActivity_PatId1_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        internal static string FindRxSitesByCommentOrPatternActivity_PatId1_DisplayName {
            get {
                return ResourceManager.GetString("FindRxSitesByCommentOrPatternActivity_PatId1_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The substring (case insensitive) to search for in the pattern field of the Rx Site for the given patient..
        /// </summary>
        internal static string FindRxSitesByCommentOrPatternActivity_PatternFieldString_Description {
            get {
                return ResourceManager.GetString("FindRxSitesByCommentOrPatternActivity_PatternFieldString_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern String.
        /// </summary>
        internal static string FindRxSitesByCommentOrPatternActivity_PatternFieldString_DisplayName {
            get {
                return ResourceManager.GetString("FindRxSitesByCommentOrPatternActivity_PatternFieldString_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rx Sites by Pcp_Id.
        /// </summary>
        internal static string FindRxSitesByPcpIdActivity_DisplayName {
            get {
                return ResourceManager.GetString("FindRxSitesByPcpIdActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The patient ID (_patId1) for which to return Rx Sites..
        /// </summary>
        internal static string FindRxSitesByPcpIdActivity_PatId_Description {
            get {
                return ResourceManager.GetString("FindRxSitesByPcpIdActivity_PatId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        internal static string FindRxSitesByPcpIdActivity_PatId_DisplayName {
            get {
                return ResourceManager.GetString("FindRxSitesByPcpIdActivity_PatId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Course ID (Pcp_Id) for which to return the Rx Site object from the database.
        /// </summary>
        internal static string FindRxSitesByPcpIdActivity_PcpId_Description {
            get {
                return ResourceManager.GetString("FindRxSitesByPcpIdActivity_PcpId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Careplan (Course).
        /// </summary>
        internal static string FindRxSitesByPcpIdActivity_PcpId_DisplayName {
            get {
                return ResourceManager.GetString("FindRxSitesByPcpIdActivity_PcpId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rx Sites by Site Name.
        /// </summary>
        internal static string FindRxSitesBySiteNameActivity_DisplayName {
            get {
                return ResourceManager.GetString("FindRxSitesBySiteNameActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The patient ID (_patId1) for which to retrieve Rx Site
        ///       records.
        /// </summary>
        internal static string FindRxSitesBySiteNameActivity_PatId1_Description {
            get {
                return ResourceManager.GetString("FindRxSitesBySiteNameActivity_PatId1_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        internal static string FindRxSitesBySiteNameActivity_PatId1_DisplayName {
            get {
                return ResourceManager.GetString("FindRxSitesBySiteNameActivity_PatId1_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String to match part or all of the Site&apos;s name (case insensitive).
        /// </summary>
        internal static string FindRxSitesBySiteNameActivity_SiteName_Description {
            get {
                return ResourceManager.GetString("FindRxSitesBySiteNameActivity_SiteName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Name.
        /// </summary>
        internal static string FindRxSitesBySiteNameActivity_SiteName_DisplayName {
            get {
                return ResourceManager.GetString("FindRxSitesBySiteNameActivity_SiteName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treatment Fields by Sit_Id.
        /// </summary>
        internal static string FindTxFieldsBySitIdActivity_DisplayName {
            get {
                return ResourceManager.GetString("FindTxFieldsBySitIdActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The patient ID (_patId1) for which to retrieve Tx Field objects.
        /// </summary>
        internal static string FindTxFieldsBySitIdActivity_PatId_Description {
            get {
                return ResourceManager.GetString("FindTxFieldsBySitIdActivity_PatId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        internal static string FindTxFieldsBySitIdActivity_PatId_DisplayName {
            get {
                return ResourceManager.GetString("FindTxFieldsBySitIdActivity_PatId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The primary key of the Site (Sit_Id) for which to return Tx Field objects from the database.
        /// </summary>
        internal static string FindTxFieldsBySitIdActivity_SitId_Description {
            get {
                return ResourceManager.GetString("FindTxFieldsBySitIdActivity_SitId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        internal static string FindTxFieldsBySitIdActivity_SitId_DisplayName {
            get {
                return ResourceManager.GetString("FindTxFieldsBySitIdActivity_SitId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        internal static string Patient_Category {
            get {
                return ResourceManager.GetString("Patient_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queries.
        /// </summary>
        internal static string Queries_ActivityGroup {
            get {
                return ResourceManager.GetString("Queries_ActivityGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radiation Oncology.
        /// </summary>
        internal static string RadiationOncology_Category {
            get {
                return ResourceManager.GetString("RadiationOncology_Category", resourceCulture);
            }
        }
    }
}
