//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impac.Mosaiq.IQ.Configuration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Impac.Mosaiq.IQ.Configuration.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An appointment script type can be used by any IQ Enabled Feature which is related to an appointment..
        /// </summary>
        internal static string AppointmentScript_Description {
            get {
                return ResourceManager.GetString("AppointmentScript_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment Script.
        /// </summary>
        internal static string AppointmentScript_Name {
            get {
                return ResourceManager.GetString("AppointmentScript_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing.
        /// </summary>
        internal static string Category_Billing {
            get {
                return ResourceManager.GetString("Category_Billing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        internal static string Category_Common {
            get {
                return ResourceManager.GetString("Category_Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DICOM.
        /// </summary>
        internal static string Category_DICOM {
            get {
                return ResourceManager.GetString("Category_DICOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Charting.
        /// </summary>
        internal static string Category_GeneralCharting {
            get {
                return ResourceManager.GetString("Category_GeneralCharting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Oncology.
        /// </summary>
        internal static string Category_MedOnc {
            get {
                return ResourceManager.GetString("Category_MedOnc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radiation Oncology.
        /// </summary>
        internal static string Category_RadiationOncology {
            get {
                return ResourceManager.GetString("Category_RadiationOncology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radiation Oncology.
        /// </summary>
        internal static string Category_RadOnc {
            get {
                return ResourceManager.GetString("Category_RadOnc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IQ script user interface trigger which is invoked when CDS care plan is imported and assigned to a patient..
        /// </summary>
        internal static string CdsCarePlanApproved_Description {
            get {
                return ResourceManager.GetString("CdsCarePlanApproved_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CDS Care Plan Approved.
        /// </summary>
        internal static string CdsCarePlanApproved_Name {
            get {
                return ResourceManager.GetString("CdsCarePlanApproved_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IQ script user interface trigger which is invoked when importing CDS care plan is canceled..
        /// </summary>
        internal static string CdsCarePlanCanceled_Description {
            get {
                return ResourceManager.GetString("CdsCarePlanCanceled_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CDS Care Plan Canceled.
        /// </summary>
        internal static string CdsCarePlanCanceled_Name {
            get {
                return ResourceManager.GetString("CdsCarePlanCanceled_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CDS Care Plan Error Occurred.
        /// </summary>
        internal static string CdsCarePlanError_Description {
            get {
                return ResourceManager.GetString("CdsCarePlanError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CDS Care Plan Error.
        /// </summary>
        internal static string CdsCarePlanError_Name {
            get {
                return ResourceManager.GetString("CdsCarePlanError_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinical Decision Support Care Plan Script Description.
        /// </summary>
        internal static string CdsCarePlanForm_Description {
            get {
                return ResourceManager.GetString("CdsCarePlanForm_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinical Decision Support Care Plan Script.
        /// </summary>
        internal static string CdsCarePlanForm_Name {
            get {
                return ResourceManager.GetString("CdsCarePlanForm_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IQ script user interface trigger which is invoked when CDS care plan is imported in pending status..
        /// </summary>
        internal static string CdsCarePlanPending_Description {
            get {
                return ResourceManager.GetString("CdsCarePlanPending_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CDS Care Plan Pending.
        /// </summary>
        internal static string CdsCarePlanPending_Name {
            get {
                return ResourceManager.GetString("CdsCarePlanPending_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IQ script user interface trigger which is invoked when user selected a similar care plan from the MOSAIQ care plan library..
        /// </summary>
        internal static string CdsCarePlanSelectedLibrary_Description {
            get {
                return ResourceManager.GetString("CdsCarePlanSelectedLibrary_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CDS MOSAIQ Care Plan Selection.
        /// </summary>
        internal static string CdsCarePlanSelectedLibrary_Name {
            get {
                return ResourceManager.GetString("CdsCarePlanSelectedLibrary_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A charge script type can be used by any IQ Enabled Feature which is related to a single charge.  For example, Code Captured..
        /// </summary>
        internal static string ChargeScript_Description {
            get {
                return ResourceManager.GetString("ChargeScript_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge Script.
        /// </summary>
        internal static string ChargeScript_Name {
            get {
                return ResourceManager.GetString("ChargeScript_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IQ script trigger which is invoked after a charge has been captured..
        /// </summary>
        internal static string ChgCodeCaptured_Decription {
            get {
                return ResourceManager.GetString("ChgCodeCaptured_Decription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Captured.
        /// </summary>
        internal static string ChgCodeCaptured_Name {
            get {
                return ResourceManager.GetString("ChgCodeCaptured_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Incoming CT Series.
        /// </summary>
        internal static string CTSeriesArrived_Description {
            get {
                return ResourceManager.GetString("CTSeriesArrived_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CT Series Arrived.
        /// </summary>
        internal static string CTSeriesArrived_Name {
            get {
                return ResourceManager.GetString("CTSeriesArrived_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A trigger that is invoked after a diagnosis has been affirmed.
        /// </summary>
        internal static string DiagnosisAffirmed_Description {
            get {
                return ResourceManager.GetString("DiagnosisAffirmed_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnosis Affirmed.
        /// </summary>
        internal static string DiagnosisAffirmed_Name {
            get {
                return ResourceManager.GetString("DiagnosisAffirmed_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A diagnosis script type can be used by any IQ Enabled Feature which is related to a diagnosis.  For example, Diagnosis Affirmed..
        /// </summary>
        internal static string DiagnosisScript_Description {
            get {
                return ResourceManager.GetString("DiagnosisScript_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnosis Script.
        /// </summary>
        internal static string DiagnosisScript_Name {
            get {
                return ResourceManager.GetString("DiagnosisScript_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A document script type can be used by any IQ Enabled Feature which is related to a single encounter.  For example, Inbound Document..
        /// </summary>
        internal static string DocumentScript_Description {
            get {
                return ResourceManager.GetString("DocumentScript_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Script.
        /// </summary>
        internal static string DocumentScript_Name {
            get {
                return ResourceManager.GetString("DocumentScript_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An IQ Script type that must be used for scripts that implement eScribe merge fields.
        /// </summary>
        internal static string EscribeMergeFieldScript_Description {
            get {
                return ResourceManager.GetString("EscribeMergeFieldScript_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eSCRIBE Merge Field.
        /// </summary>
        internal static string EscribeMergeFieldScript_Name {
            get {
                return ResourceManager.GetString("EscribeMergeFieldScript_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A script type that is used by an internal script that selects an eScribe template based on a document type and a patient&apos;s diagnosis..
        /// </summary>
        internal static string EscribeSelectTemplate_Description {
            get {
                return ResourceManager.GetString("EscribeSelectTemplate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select eSCRIBE Template.
        /// </summary>
        internal static string EscribeSelectTemplate_Name {
            get {
                return ResourceManager.GetString("EscribeSelectTemplate_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An IQ script which can be invoked from any decision support trigger point..
        /// </summary>
        internal static string GenericScript_Description {
            get {
                return ResourceManager.GetString("GenericScript_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic Script.
        /// </summary>
        internal static string GenericScript_Name {
            get {
                return ResourceManager.GetString("GenericScript_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Image Series Script.
        /// </summary>
        internal static string ImageSeriesScript_Description {
            get {
                return ResourceManager.GetString("ImageSeriesScript_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Series Script.
        /// </summary>
        internal static string ImageSeriesScript_Name {
            get {
                return ResourceManager.GetString("ImageSeriesScript_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inbound Document.
        /// </summary>
        internal static string InboudDocument_Name {
            get {
                return ResourceManager.GetString("InboudDocument_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A trigger that is invoked after the import of a new interfaced document.
        /// </summary>
        internal static string InboundDocument_Description {
            get {
                return ResourceManager.GetString("InboundDocument_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A trigger that is invoked after the import of a new ObsReq record.
        /// </summary>
        internal static string InboundObsReq_Description {
            get {
                return ResourceManager.GetString("InboundObsReq_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inbound Observation Data.
        /// </summary>
        internal static string InboundObsReq_Name {
            get {
                return ResourceManager.GetString("InboundObsReq_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compute Isocenter Position for iViewGT RTImage.
        /// </summary>
        internal static string IViewGTAutoIsocenter_Description {
            get {
                return ResourceManager.GetString("IViewGTAutoIsocenter_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iViewGT Auto-Isocenter.
        /// </summary>
        internal static string IViewGTAutoIsocenter_Name {
            get {
                return ResourceManager.GetString("IViewGTAutoIsocenter_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compute Isocenter Position for iViewGT RTImage.
        /// </summary>
        internal static string IViewGTAutoIsocenterScript_Description {
            get {
                return ResourceManager.GetString("IViewGTAutoIsocenterScript_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iViewGT Auto-Isocenter Script.
        /// </summary>
        internal static string IViewGTAutoIsocenterScript_Name {
            get {
                return ResourceManager.GetString("IViewGTAutoIsocenterScript_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Incoming MR Series.
        /// </summary>
        internal static string MRSeriesArrived_Description {
            get {
                return ResourceManager.GetString("MRSeriesArrived_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MR Series Arrived.
        /// </summary>
        internal static string MRSeriesArrived_Name {
            get {
                return ResourceManager.GetString("MRSeriesArrived_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IQ script trigger which is invoked after the observation data has been created..
        /// </summary>
        internal static string ObsDataCreated_Description {
            get {
                return ResourceManager.GetString("ObsDataCreated_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observation Data Created.
        /// </summary>
        internal static string ObsDataCreated_Name {
            get {
                return ResourceManager.GetString("ObsDataCreated_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IQ script trigger which is invoked after the observation data has been reviewed..
        /// </summary>
        internal static string ObsDataReviewed_Description {
            get {
                return ResourceManager.GetString("ObsDataReviewed_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observation Data Reviewed.
        /// </summary>
        internal static string ObsDataReviewed_Name {
            get {
                return ResourceManager.GetString("ObsDataReviewed_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IQ script trigger which is invoked after the observation order has been approved..
        /// </summary>
        internal static string ObsOrdApproved_Description {
            get {
                return ResourceManager.GetString("ObsOrdApproved_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Approved.
        /// </summary>
        internal static string ObsOrdApproved_Name {
            get {
                return ResourceManager.GetString("ObsOrdApproved_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IQ script trigger which is invoked prior to the observation order has been approved..
        /// </summary>
        internal static string ObsOrdApproving_Description {
            get {
                return ResourceManager.GetString("ObsOrdApproving_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Approving.
        /// </summary>
        internal static string ObsOrdApproving_Name {
            get {
                return ResourceManager.GetString("ObsOrdApproving_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IQ script trigger which is invoked when the observation order has been created..
        /// </summary>
        internal static string ObsOrdCreated_Description {
            get {
                return ResourceManager.GetString("ObsOrdCreated_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Created.
        /// </summary>
        internal static string ObsOrdCreated_Name {
            get {
                return ResourceManager.GetString("ObsOrdCreated_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IQ script trigger which is invoked after a observation order is marked ready to treat..
        /// </summary>
        internal static string ObsOrdMarkedReadyToTreat_Description {
            get {
                return ResourceManager.GetString("ObsOrdMarkedReadyToTreat_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Marked Ready to Treat.
        /// </summary>
        internal static string ObsOrdMarkedReadyToTreat_Name {
            get {
                return ResourceManager.GetString("ObsOrdMarkedReadyToTreat_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IQ script trigger which is invoked as a observation order is being marked ready to treat..
        /// </summary>
        internal static string ObsOrdMarkingReadyToTreat_Description {
            get {
                return ResourceManager.GetString("ObsOrdMarkingReadyToTreat_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Marking Ready to Treat.
        /// </summary>
        internal static string ObsOrdMarkingReadyToTreat_Name {
            get {
                return ResourceManager.GetString("ObsOrdMarkingReadyToTreat_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IQ script trigger which is invoked after the observation order has been modified..
        /// </summary>
        internal static string ObsOrdModified_Description {
            get {
                return ResourceManager.GetString("ObsOrdModified_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Modified.
        /// </summary>
        internal static string ObsOrdModified_Name {
            get {
                return ResourceManager.GetString("ObsOrdModified_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An observation data script type can be used by any IQ Enabled Feature which is related to a single observation data item.  For example, Observation Data Created or Observation Data Reviewed..
        /// </summary>
        internal static string ObsReqScript_Description {
            get {
                return ResourceManager.GetString("ObsReqScript_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observation Data Script.
        /// </summary>
        internal static string ObsReqScript_Name {
            get {
                return ResourceManager.GetString("ObsReqScript_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An order script type can be used by any IQ Enabled Feature which is related to a single order. For example, Observation Order Approved or Observation Order Created are actions which take an order as input by the script..
        /// </summary>
        internal static string OrderScript_Description {
            get {
                return ResourceManager.GetString("OrderScript_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Script.
        /// </summary>
        internal static string OrderScript_Name {
            get {
                return ResourceManager.GetString("OrderScript_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An order script type can be used by any IQ Enabled Feature which is related to a single order and is a cancelable action.  For example, Pharmacy Order Approval, or Pharmacy Order Verifying are actions which take an order as input and can be cancelled by the script if needed..
        /// </summary>
        internal static string OrderScriptCancelable_Description {
            get {
                return ResourceManager.GetString("OrderScriptCancelable_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Script (Cancelable).
        /// </summary>
        internal static string OrderScriptCancelable_Name {
            get {
                return ResourceManager.GetString("OrderScriptCancelable_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The patient care plan form script type allows additional IQ Engine functionality to be executed upon particular actions that occur in a form (such as changing a control value, clicking OK, or clicking Cancel)..
        /// </summary>
        internal static string PatientCarePlanForm_Description {
            get {
                return ResourceManager.GetString("PatientCarePlanForm_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IQ script user interface trigger which is invoked upon opening a Patient Care Plan form..
        /// </summary>
        internal static string PatientCarePlanFormFeature_Description {
            get {
                return ResourceManager.GetString("PatientCarePlanFormFeature_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Care Plan Form.
        /// </summary>
        internal static string PatientCarePlanFormFeature_Name {
            get {
                return ResourceManager.GetString("PatientCarePlanFormFeature_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Care Plan Form Script.
        /// </summary>
        internal static string PatientCarePlanFormScript_Name {
            get {
                return ResourceManager.GetString("PatientCarePlanFormScript_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IQ script trigger which is invoked after the incorporation of a CCDA document.
        /// </summary>
        internal static string PatientCCdaReceipt_Description {
            get {
                return ResourceManager.GetString("PatientCCdaReceipt_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCDA Receipt.
        /// </summary>
        internal static string PatientCCdaReceipt_Name {
            get {
                return ResourceManager.GetString("PatientCCdaReceipt_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IQ script trigger which is invoked when the Review Chart command is invoked.
        /// </summary>
        internal static string PatientChartReview_Description {
            get {
                return ResourceManager.GetString("PatientChartReview_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Chart.
        /// </summary>
        internal static string PatientChartReview_Name {
            get {
                return ResourceManager.GetString("PatientChartReview_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IQ script trigger which is invoked after patient&apos;s diagnosis has been reconciled.
        /// </summary>
        internal static string PatientDiagnosisReconciled_Description {
            get {
                return ResourceManager.GetString("PatientDiagnosisReconciled_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnosis Reconciled.
        /// </summary>
        internal static string PatientDiagnosisReconciled_Name {
            get {
                return ResourceManager.GetString("PatientDiagnosisReconciled_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IQ script trigger which is invoked after patient&apos;s medications have been reconciled.
        /// </summary>
        internal static string PatientMedicationsReconciled_Description {
            get {
                return ResourceManager.GetString("PatientMedicationsReconciled_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medications Reconciled.
        /// </summary>
        internal static string PatientMedicationsReconciled_Name {
            get {
                return ResourceManager.GetString("PatientMedicationsReconciled_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IQ script trigger which is invoked after opening a patient&apos;s chart.
        /// </summary>
        internal static string PatientOpenChart_Description {
            get {
                return ResourceManager.GetString("PatientOpenChart_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Patient Chart.
        /// </summary>
        internal static string PatientOpenChart_Name {
            get {
                return ResourceManager.GetString("PatientOpenChart_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An IQ script that can be invoked on any supported, patient related operations..
        /// </summary>
        internal static string PatientScript_Description {
            get {
                return ResourceManager.GetString("PatientScript_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Script.
        /// </summary>
        internal static string PatientScript_Name {
            get {
                return ResourceManager.GetString("PatientScript_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A patient script type can be used by any IQ enabled feature which is related to a patient.  In some cases, the patient whose chart is currently opened will be used while in other cases, the patient tied to the data context of the IQ enabled feature will be used.  For example, if you attach a Patient Script (Cancelable) to an order trigger point, the patient the order belongs to will be used..
        /// </summary>
        internal static string PatientScriptCancelable_Description {
            get {
                return ResourceManager.GetString("PatientScriptCancelable_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Script (Cancelable).
        /// </summary>
        internal static string PatientScriptCancelable_Name {
            get {
                return ResourceManager.GetString("PatientScriptCancelable_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Incoming PET Series.
        /// </summary>
        internal static string PETSeriesArrived_Description {
            get {
                return ResourceManager.GetString("PETSeriesArrived_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PET Series Arrived.
        /// </summary>
        internal static string PETSeriesArrived_Name {
            get {
                return ResourceManager.GetString("PETSeriesArrived_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IQ script trigger which is invoked after a pharmacy order is administered..
        /// </summary>
        internal static string PharmOrdAdministered_Description {
            get {
                return ResourceManager.GetString("PharmOrdAdministered_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Administered.
        /// </summary>
        internal static string PharmOrdAdministered_Name {
            get {
                return ResourceManager.GetString("PharmOrdAdministered_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IQ script trigger which is invoked as a pharmacy order is being administered..
        /// </summary>
        internal static string PharmOrdAdministering_Description {
            get {
                return ResourceManager.GetString("PharmOrdAdministering_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Administering.
        /// </summary>
        internal static string PharmOrdAdministering_Name {
            get {
                return ResourceManager.GetString("PharmOrdAdministering_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IQ script trigger which is invoked after a pharmacy order is approved..
        /// </summary>
        internal static string PharmOrdApproved_Description {
            get {
                return ResourceManager.GetString("PharmOrdApproved_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Approved.
        /// </summary>
        internal static string PharmOrdApproved_Name {
            get {
                return ResourceManager.GetString("PharmOrdApproved_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IQ script trigger which is invoked as a pharmacy order is being approved..
        /// </summary>
        internal static string PharmOrdApproving_Description {
            get {
                return ResourceManager.GetString("PharmOrdApproving_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Approving.
        /// </summary>
        internal static string PharmOrdApproving_Name {
            get {
                return ResourceManager.GetString("PharmOrdApproving_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IQ script trigger which is invoked after a pharmacy order is created..
        /// </summary>
        internal static string PharmOrdCreated_Description {
            get {
                return ResourceManager.GetString("PharmOrdCreated_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Created.
        /// </summary>
        internal static string PharmOrdCreated_Name {
            get {
                return ResourceManager.GetString("PharmOrdCreated_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IQ script trigger which is invoked after a pharmacy order is marked ready to treat..
        /// </summary>
        internal static string PharmOrdMarkedReadyToTreat_Description {
            get {
                return ResourceManager.GetString("PharmOrdMarkedReadyToTreat_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Marked Ready to Treat.
        /// </summary>
        internal static string PharmOrdMarkedReadyToTreat_Name {
            get {
                return ResourceManager.GetString("PharmOrdMarkedReadyToTreat_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IQ script trigger which is invoked as a pharmacy order is being marked ready to treat..
        /// </summary>
        internal static string PharmOrdMarkingReadyToTreat_Description {
            get {
                return ResourceManager.GetString("PharmOrdMarkingReadyToTreat_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Marking Ready to Treat.
        /// </summary>
        internal static string PharmOrdMarkingReadyToTreat_Name {
            get {
                return ResourceManager.GetString("PharmOrdMarkingReadyToTreat_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IQ script trigger which is invoked after a pharmacy order is modified..
        /// </summary>
        internal static string PharmOrdModified_Description {
            get {
                return ResourceManager.GetString("PharmOrdModified_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Modified.
        /// </summary>
        internal static string PharmOrdModified_Name {
            get {
                return ResourceManager.GetString("PharmOrdModified_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IQ script trigger which is invoked after a pharmacy order is prepped..
        /// </summary>
        internal static string PharmOrdPrepped_Description {
            get {
                return ResourceManager.GetString("PharmOrdPrepped_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Prepped.
        /// </summary>
        internal static string PharmOrdPrepped_Name {
            get {
                return ResourceManager.GetString("PharmOrdPrepped_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IQ script trigger which is invoked as a pharmacy order is being prepped..
        /// </summary>
        internal static string PharmOrdPrepping_Description {
            get {
                return ResourceManager.GetString("PharmOrdPrepping_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Prepping.
        /// </summary>
        internal static string PharmOrdPrepping_Name {
            get {
                return ResourceManager.GetString("PharmOrdPrepping_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IQ script trigger which is invoked after a pharmacy order is verified..
        /// </summary>
        internal static string PharmOrdVerified_Description {
            get {
                return ResourceManager.GetString("PharmOrdVerified_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Verified.
        /// </summary>
        internal static string PharmOrdVerified_Name {
            get {
                return ResourceManager.GetString("PharmOrdVerified_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IQ script trigger which is invoked as a pharmacy order is being verified..
        /// </summary>
        internal static string PharmOrdVerifying_Description {
            get {
                return ResourceManager.GetString("PharmOrdVerifying_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Verifying.
        /// </summary>
        internal static string PharmOrdVerifying_Name {
            get {
                return ResourceManager.GetString("PharmOrdVerifying_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PotD script type is used by the PotD IQ enabled feature..
        /// </summary>
        internal static string PotdScriptCancelable_Description {
            get {
                return ResourceManager.GetString("PotdScriptCancelable_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PotD Script (Cancelable).
        /// </summary>
        internal static string PotdScriptCancelable_Name {
            get {
                return ResourceManager.GetString("PotdScriptCancelable_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purge AVS for Image Series.
        /// </summary>
        internal static string PurgeAVS_Description {
            get {
                return ResourceManager.GetString("PurgeAVS_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purge AVS for Image Series.
        /// </summary>
        internal static string PurgeAVS_Name {
            get {
                return ResourceManager.GetString("PurgeAVS_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purge AVS Script.
        /// </summary>
        internal static string PurgeAVSScript_Description {
            get {
                return ResourceManager.GetString("PurgeAVSScript_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purge AVS Script.
        /// </summary>
        internal static string PurgeAVSScript_Name {
            get {
                return ResourceManager.GetString("PurgeAVSScript_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An IQ Script which is invoked when a QCL task is completed..
        /// </summary>
        internal static string QclCompleted_Description {
            get {
                return ResourceManager.GetString("QclCompleted_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QCL Completed.
        /// </summary>
        internal static string QclCompleted_Name {
            get {
                return ResourceManager.GetString("QclCompleted_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A QCL script type can be used by any IQ Enabled Feature which is related to a single quality check list item.  For example, QCL completed or QCL skipped..
        /// </summary>
        internal static string QclScript_Description {
            get {
                return ResourceManager.GetString("QclScript_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QCL Script.
        /// </summary>
        internal static string QclScript_Name {
            get {
                return ResourceManager.GetString("QclScript_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An IQ Script which is invoked when a QCL task is skipped..
        /// </summary>
        internal static string QclSkipped_Description {
            get {
                return ResourceManager.GetString("QclSkipped_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QCL Skipped.
        /// </summary>
        internal static string QclSkipped_Name {
            get {
                return ResourceManager.GetString("QclSkipped_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IQ script trigger which is invoked when a quick order is generated..
        /// </summary>
        internal static string QuickOrderGenerateFeature_Description {
            get {
                return ResourceManager.GetString("QuickOrderGenerateFeature_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Order Generate.
        /// </summary>
        internal static string QuickOrderGenerateFeature_Name {
            get {
                return ResourceManager.GetString("QuickOrderGenerateFeature_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An IQ Script which can be executed on Quick Order generation..
        /// </summary>
        internal static string QuickOrderGenerateScript_Description {
            get {
                return ResourceManager.GetString("QuickOrderGenerateScript_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regenerate AVS for Image Series.
        /// </summary>
        internal static string RegenerateAVS_Description {
            get {
                return ResourceManager.GetString("RegenerateAVS_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regenerate AVS for Image Series.
        /// </summary>
        internal static string RegenerateAVS_Name {
            get {
                return ResourceManager.GetString("RegenerateAVS_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regenerate AVS Script.
        /// </summary>
        internal static string RegenerateAVSScript_Description {
            get {
                return ResourceManager.GetString("RegenerateAVSScript_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regenerate AVS Script.
        /// </summary>
        internal static string RegenerateAVSScript_Name {
            get {
                return ResourceManager.GetString("RegenerateAVSScript_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PotD Treat.
        /// </summary>
        internal static string RODoseChartPotdTreat {
            get {
                return ResourceManager.GetString("RODoseChartPotdTreat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PotD-only trigger point for Radiotherapy treatment.
        /// </summary>
        internal static string RODoseChartPotdTreat_Description {
            get {
                return ResourceManager.GetString("RODoseChartPotdTreat_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QA Mode.
        /// </summary>
        internal static string RODoseChartQAMode {
            get {
                return ResourceManager.GetString("RODoseChartQAMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger point for the QA Mode in the Treatment Chart.
        /// </summary>
        internal static string RODoseChartQAMode_Description {
            get {
                return ResourceManager.GetString("RODoseChartQAMode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treat.
        /// </summary>
        internal static string RODoseChartTreat {
            get {
                return ResourceManager.GetString("RODoseChartTreat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger point for the Radiotherapy treatment in the Treatment Chart.
        /// </summary>
        internal static string RODoseChartTreat_Description {
            get {
                return ResourceManager.GetString("RODoseChartTreat_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RPS XVIReference Parameter Set instance arrived.
        /// </summary>
        internal static string RPSInstanceArrived_Description {
            get {
                return ResourceManager.GetString("RPSInstanceArrived_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RPS Instance Arrived.
        /// </summary>
        internal static string RPSInstanceArrived_Name {
            get {
                return ResourceManager.GetString("RPSInstanceArrived_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RPS Instance Script Desc.
        /// </summary>
        internal static string RPSInstanceScript_Description {
            get {
                return ResourceManager.GetString("RPSInstanceScript_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RPS Instance Script.
        /// </summary>
        internal static string RPSInstanceScript_Name {
            get {
                return ResourceManager.GetString("RPSInstanceScript_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Incoming RT Dose Instance.
        /// </summary>
        internal static string RTDoseInstanceArrived_Description {
            get {
                return ResourceManager.GetString("RTDoseInstanceArrived_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RT Dose Instance Arrived.
        /// </summary>
        internal static string RTDoseInstanceArrived_Name {
            get {
                return ResourceManager.GetString("RTDoseInstanceArrived_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Incoming RT Dose Instance.
        /// </summary>
        internal static string RTDoseInstanceScript_Description {
            get {
                return ResourceManager.GetString("RTDoseInstanceScript_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RT Dose Instance Script.
        /// </summary>
        internal static string RTDoseInstanceScript_Name {
            get {
                return ResourceManager.GetString("RTDoseInstanceScript_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Incoming RT Plan Instance.
        /// </summary>
        internal static string RTPlanInstanceArrived_Description {
            get {
                return ResourceManager.GetString("RTPlanInstanceArrived_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RT Plan Instance Arrived.
        /// </summary>
        internal static string RTPlanInstanceArrived_Name {
            get {
                return ResourceManager.GetString("RTPlanInstanceArrived_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Incoming RT Plan Instance.
        /// </summary>
        internal static string RTPlanInstanceScript_Description {
            get {
                return ResourceManager.GetString("RTPlanInstanceScript_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RT Plan Instance Script.
        /// </summary>
        internal static string RTPlanInstanceScript_Name {
            get {
                return ResourceManager.GetString("RTPlanInstanceScript_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IQ script trigger which is invoked after the appointment is marked ended..
        /// </summary>
        internal static string SchAppointementEnded_Description {
            get {
                return ResourceManager.GetString("SchAppointementEnded_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment Ended.
        /// </summary>
        internal static string SchAppointmentEnded_Name {
            get {
                return ResourceManager.GetString("SchAppointmentEnded_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IQ script trigger which is invoked when a new appointment or a wave is scheduled on the Appointment Slip window. The trigger is also invoked when the activity for an existing appointment is changed on the Appointment Slip window.
        ///Scheduling appointments via series, or scheduling pending appointments by drag and drop is not supported..
        /// </summary>
        internal static string SchAppointmentScheduled_Description {
            get {
                return ResourceManager.GetString("SchAppointmentScheduled_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment Scheduled.
        /// </summary>
        internal static string SchAppointmentScheduled_Name {
            get {
                return ResourceManager.GetString("SchAppointmentScheduled_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IQ script trigger which is invoked after the appointment is marked patient queued..
        /// </summary>
        internal static string SchPatientQueued_Description {
            get {
                return ResourceManager.GetString("SchPatientQueued_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Queued.
        /// </summary>
        internal static string SchPatientQueued_Name {
            get {
                return ResourceManager.GetString("SchPatientQueued_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an eSCRIBE template.
        /// </summary>
        internal static string SelectTemplate_Description {
            get {
                return ResourceManager.GetString("SelectTemplate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select eSCRIBE Template.
        /// </summary>
        internal static string SelectTemplate_Name {
            get {
                return ResourceManager.GetString("SelectTemplate_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Incoming Spatial Registration Instance.
        /// </summary>
        internal static string SROInstanceArrived_Description {
            get {
                return ResourceManager.GetString("SROInstanceArrived_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SRO Instance Arrived.
        /// </summary>
        internal static string SROInstanceArrived_Name {
            get {
                return ResourceManager.GetString("SROInstanceArrived_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Incoming Spatial Registration Instance.
        /// </summary>
        internal static string SROInstanceScript_Description {
            get {
                return ResourceManager.GetString("SROInstanceScript_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SRO Instance Script.
        /// </summary>
        internal static string SROInstanceScript_Name {
            get {
                return ResourceManager.GetString("SROInstanceScript_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Incoming Structure Set Instance.
        /// </summary>
        internal static string StructureSetInstanceArrived_Description {
            get {
                return ResourceManager.GetString("StructureSetInstanceArrived_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structure Set  Instance Arrived.
        /// </summary>
        internal static string StructureSetInstanceArrived_Name {
            get {
                return ResourceManager.GetString("StructureSetInstanceArrived_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Incoming Structure Set Instance.
        /// </summary>
        internal static string StructureSetInstanceScript_Description {
            get {
                return ResourceManager.GetString("StructureSetInstanceScript_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structure Set Instance Script.
        /// </summary>
        internal static string StructureSetInstanceScript_Name {
            get {
                return ResourceManager.GetString("StructureSetInstanceScript_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointments.
        /// </summary>
        internal static string SubCategory_Appointments {
            get {
                return ResourceManager.GetString("SubCategory_Appointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Care Plans.
        /// </summary>
        internal static string SubCategory_CarePlans {
            get {
                return ResourceManager.GetString("SubCategory_CarePlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CDS Care Plans.
        /// </summary>
        internal static string SubCategory_CdsCarePlans {
            get {
                return ResourceManager.GetString("SubCategory_CdsCarePlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge.
        /// </summary>
        internal static string SubCategory_Charge {
            get {
                return ResourceManager.GetString("SubCategory_Charge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        internal static string SubCategory_Common {
            get {
                return ResourceManager.GetString("SubCategory_Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnosis.
        /// </summary>
        internal static string SubCategory_Diagnosis {
            get {
                return ResourceManager.GetString("SubCategory_Diagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DICOM Instances.
        /// </summary>
        internal static string SubCategory_DicomInstances {
            get {
                return ResourceManager.GetString("SubCategory_DicomInstances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DICOM Series.
        /// </summary>
        internal static string SubCategory_DicomSeries {
            get {
                return ResourceManager.GetString("SubCategory_DicomSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eSCRIBE.
        /// </summary>
        internal static string SubCategory_Escribe {
            get {
                return ResourceManager.GetString("SubCategory_Escribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observation Data.
        /// </summary>
        internal static string SubCategory_ObservationData {
            get {
                return ResourceManager.GetString("SubCategory_ObservationData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observation Orders.
        /// </summary>
        internal static string SubCategory_ObservationOrders {
            get {
                return ResourceManager.GetString("SubCategory_ObservationOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observation Data.
        /// </summary>
        internal static string SubCategory_ObsReq {
            get {
                return ResourceManager.GetString("SubCategory_ObsReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        internal static string SubCategory_Orders {
            get {
                return ResourceManager.GetString("SubCategory_Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        internal static string SubCategory_Patient {
            get {
                return ResourceManager.GetString("SubCategory_Patient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pharmacy Orders.
        /// </summary>
        internal static string SubCategory_PharmacyOrders {
            get {
                return ResourceManager.GetString("SubCategory_PharmacyOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality Check List.
        /// </summary>
        internal static string SubCategory_Qcl {
            get {
                return ResourceManager.GetString("SubCategory_Qcl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treatment Chart.
        /// </summary>
        internal static string SubCategory_TreatmentChart {
            get {
                return ResourceManager.GetString("SubCategory_TreatmentChart", resourceCulture);
            }
        }
    }
}
