//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impac.Mosaiq.IQ.Activities.Tools {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Impac.Mosaiq.IQ.Activities.Tools.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The action denied to the user..
        /// </summary>
        internal static string AccessDeniedMessageBoxActivity_Action_Description {
            get {
                return ResourceManager.GetString("AccessDeniedMessageBoxActivity_Action_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Action.
        /// </summary>
        internal static string AccessDeniedMessageBoxActivity_Action_DisplayName {
            get {
                return ResourceManager.GetString("AccessDeniedMessageBoxActivity_Action_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Denied Message Box.
        /// </summary>
        internal static string AccessDeniedMessageBoxActivity_DisplayName {
            get {
                return ResourceManager.GetString("AccessDeniedMessageBoxActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Values.
        /// </summary>
        internal static string ActiveValue_Category {
            get {
                return ResourceManager.GetString("ActiveValue_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Data Column.
        /// </summary>
        internal static string AddDataColumn_DisplayName {
            get {
                return ResourceManager.GetString("AddDataColumn_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Data Row.
        /// </summary>
        internal static string AddDataRow_DisplayName {
            get {
                return ResourceManager.GetString("AddDataRow_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add DataRow to DataTable.
        /// </summary>
        internal static string AddRow_Description {
            get {
                return ResourceManager.GetString("AddRow_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add DataRow.
        /// </summary>
        internal static string AddRow_DisplayName {
            get {
                return ResourceManager.GetString("AddRow_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADO.NET.
        /// </summary>
        internal static string ADONet_Category {
            get {
                return ResourceManager.GetString("ADONet_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Message Box.
        /// </summary>
        internal static string AlarmMessageBoxActivity_DisplayName {
            get {
                return ResourceManager.GetString("AlarmMessageBoxActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Column Value.
        /// </summary>
        internal static string AssignColumnValue_DisplayName {
            get {
                return ResourceManager.GetString("AssignColumnValue_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The caption which will display in the message box window bar..
        /// </summary>
        internal static string Caption_Description {
            get {
                return ResourceManager.GetString("Caption_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caption.
        /// </summary>
        internal static string Caption_DisplayName {
            get {
                return ResourceManager.GetString("Caption_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caution Message Box.
        /// </summary>
        internal static string CautionMessageBoxActivity_DisplayName {
            get {
                return ResourceManager.GetString("CautionMessageBoxActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataType of the column.
        /// </summary>
        internal static string ColumnDataType_Description {
            get {
                return ResourceManager.GetString("ColumnDataType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column DataType.
        /// </summary>
        internal static string ColumnDataType_DisplayName {
            get {
                return ResourceManager.GetString("ColumnDataType_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the column to be added.
        /// </summary>
        internal static string ColumnName_Description {
            get {
                return ResourceManager.GetString("ColumnName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Name.
        /// </summary>
        internal static string ColumnName_DisplayName {
            get {
                return ResourceManager.GetString("ColumnName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Data Table.
        /// </summary>
        internal static string CreateDataTable_DisplayName {
            get {
                return ResourceManager.GetString("CreateDataTable_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Access.
        /// </summary>
        internal static string Database_Category {
            get {
                return ResourceManager.GetString("Database_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataRow to be added.
        /// </summary>
        internal static string DataRow_Description {
            get {
                return ResourceManager.GetString("DataRow_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataRow.
        /// </summary>
        internal static string DataRow_DisplayName {
            get {
                return ResourceManager.GetString("DataRow_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataTable object created using the given name.
        /// </summary>
        internal static string DataTable_Description {
            get {
                return ResourceManager.GetString("DataTable_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataTable.
        /// </summary>
        internal static string DataTable_DisplayName {
            get {
                return ResourceManager.GetString("DataTable_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the table to create.
        /// </summary>
        internal static string DataTableName_Description {
            get {
                return ResourceManager.GetString("DataTableName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Name.
        /// </summary>
        internal static string DataTableName_DisplayName {
            get {
                return ResourceManager.GetString("DataTableName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Value.
        /// </summary>
        internal static string DataValue_Description {
            get {
                return ResourceManager.GetString("DataValue_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Value.
        /// </summary>
        internal static string DataValue_DisplayName {
            get {
                return ResourceManager.GetString("DataValue_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        internal static string Debug_Category {
            get {
                return ResourceManager.GetString("Debug_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default button selected when the message box opens..
        /// </summary>
        internal static string DefaultButtons_Description {
            get {
                return ResourceManager.GetString("DefaultButtons_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Buttons.
        /// </summary>
        internal static string DefaultButtons_DisplayName {
            get {
                return ResourceManager.GetString("DefaultButtons_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The result of the user&apos;s selection in the message box..
        /// </summary>
        internal static string DialogResult_Description {
            get {
                return ResourceManager.GetString("DialogResult_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog Result.
        /// </summary>
        internal static string DialogResult_DisplayName {
            get {
                return ResourceManager.GetString("DialogResult_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Message Box.
        /// </summary>
        internal static string ErrorMessageBoxActivity_DisplayName {
            get {
                return ResourceManager.GetString("ErrorMessageBoxActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal Error Message Box.
        /// </summary>
        internal static string FatalErrorMessageBoxActivity_DisplayName {
            get {
                return ResourceManager.GetString("FatalErrorMessageBoxActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Department ID..
        /// </summary>
        internal static string GetActiveDeptIdActivity_DeptId_Description {
            get {
                return ResourceManager.GetString("GetActiveDeptIdActivity_DeptId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department ID.
        /// </summary>
        internal static string GetActiveDeptIdActivity_DeptId_DisplayName {
            get {
                return ResourceManager.GetString("GetActiveDeptIdActivity_DeptId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Active Dept ID.
        /// </summary>
        internal static string GetActiveDeptIdActivity_DisplayName {
            get {
                return ResourceManager.GetString("GetActiveDeptIdActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Active Patient ID.
        /// </summary>
        internal static string GetActivePatientIdActivity_DisplayName {
            get {
                return ResourceManager.GetString("GetActivePatientIdActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Patient ID, null if no patient is selected..
        /// </summary>
        internal static string GetActivePatientIdActivity_PatientId_Description {
            get {
                return ResourceManager.GetString("GetActivePatientIdActivity_PatientId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient ID.
        /// </summary>
        internal static string GetActivePatientIdActivity_PatientId_DisplayName {
            get {
                return ResourceManager.GetString("GetActivePatientIdActivity_PatientId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Active Staff ID.
        /// </summary>
        internal static string GetActiveStaffIdActivity_DisplayName {
            get {
                return ResourceManager.GetString("GetActiveStaffIdActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Staff ID, null if no staff is logged in..
        /// </summary>
        internal static string GetActiveStaffIdActivity_StaffId_Description {
            get {
                return ResourceManager.GetString("GetActiveStaffIdActivity_StaffId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff ID.
        /// </summary>
        internal static string GetActiveStaffIdActivity_StaffId_DisplayName {
            get {
                return ResourceManager.GetString("GetActiveStaffIdActivity_StaffId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Entities (SQL).
        /// </summary>
        internal static string GetEntitiesSqlActivity_DisplayName {
            get {
                return ResourceManager.GetString("GetEntitiesSqlActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Entity By Primary Key.
        /// </summary>
        internal static string GetEntityByPrimaryKeyActivity_DisplayName {
            get {
                return ResourceManager.GetString("GetEntityByPrimaryKeyActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Entity (SQL).
        /// </summary>
        internal static string GetEntitySqlActivity_DisplayName {
            get {
                return ResourceManager.GetString("GetEntitySqlActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Persistence Manager.
        /// </summary>
        internal static string GetPersistenceManagerActivity_DisplayName {
            get {
                return ResourceManager.GetString("GetPersistenceManagerActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new persistence manager created by the activity..
        /// </summary>
        internal static string GetPersistenceManagerActivity_PersistenceManager_Description {
            get {
                return ResourceManager.GetString("GetPersistenceManagerActivity_PersistenceManager_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Runtime Cache Value.
        /// </summary>
        internal static string GetRuntimeCacheValueActivity_DisplayName {
            get {
                return ResourceManager.GetString("GetRuntimeCacheValueActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to They key of the value to lookup in the runtime value cache..
        /// </summary>
        internal static string GetRuntimeCacheValueActivity_Key_Description {
            get {
                return ResourceManager.GetString("GetRuntimeCacheValueActivity_Key_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns whether a value was found in the runtime value cache..
        /// </summary>
        internal static string GetRuntimeCacheValueActivity_ResultFound_Description {
            get {
                return ResourceManager.GetString("GetRuntimeCacheValueActivity_ResultFound_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result Found.
        /// </summary>
        internal static string GetRuntimeCacheValueActivity_ResultFound_DisplayName {
            get {
                return ResourceManager.GetString("GetRuntimeCacheValueActivity_ResultFound_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value found in the runtime value cache..
        /// </summary>
        internal static string GetRuntimeCacheValueActivity_Value_Description {
            get {
                return ResourceManager.GetString("GetRuntimeCacheValueActivity_Value_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Runtime Metadata.
        /// </summary>
        internal static string GetRuntimeMetadata_DisplayName {
            get {
                return ResourceManager.GetString("GetRuntimeMetadata_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The primary key of the IQAssign record for the script being executed..
        /// </summary>
        internal static string GetRuntimeMetadata_IqaGuid_Description {
            get {
                return ResourceManager.GetString("GetRuntimeMetadata_IqaGuid_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IqaGuid.
        /// </summary>
        internal static string GetRuntimeMetadata_IqaGuid_DisplayName {
            get {
                return ResourceManager.GetString("GetRuntimeMetadata_IqaGuid_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The primary key of the IQPrefer record for the script being executed..
        /// </summary>
        internal static string GetRuntimeMetadata_IqpGuid_Description {
            get {
                return ResourceManager.GetString("GetRuntimeMetadata_IqpGuid_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IqpGuid.
        /// </summary>
        internal static string GetRuntimeMetadata_IqpGuid_DisplayName {
            get {
                return ResourceManager.GetString("GetRuntimeMetadata_IqpGuid_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The primary key of the IQScript record for the script being executed..
        /// </summary>
        internal static string GetRuntimeMetadata_IqsGuid_Description {
            get {
                return ResourceManager.GetString("GetRuntimeMetadata_IqsGuid_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IqsGuid.
        /// </summary>
        internal static string GetRuntimeMetadata_IqsGuid_DisplayName {
            get {
                return ResourceManager.GetString("GetRuntimeMetadata_IqsGuid_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The primary key of the IQScriptRevision record for the script being executed..
        /// </summary>
        internal static string GetRuntimeMetadata_IqsrGuid_Description {
            get {
                return ResourceManager.GetString("GetRuntimeMetadata_IqsrGuid_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IqsrGuid.
        /// </summary>
        internal static string GetRuntimeMetadata_IqsrGuid_DisplayName {
            get {
                return ResourceManager.GetString("GetRuntimeMetadata_IqsrGuid_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IScriptFeature object of the trigger point from which the current script was invoked..
        /// </summary>
        internal static string GetRuntimeMetadata_ScriptFeature_Description {
            get {
                return ResourceManager.GetString("GetRuntimeMetadata_ScriptFeature_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script Feature.
        /// </summary>
        internal static string GetRuntimeMetadata_ScriptFeature_DisplayName {
            get {
                return ResourceManager.GetString("GetRuntimeMetadata_ScriptFeature_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IScriptType object of the script being executed..
        /// </summary>
        internal static string GetRuntimeMetadata_ScriptType_Description {
            get {
                return ResourceManager.GetString("GetRuntimeMetadata_ScriptType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script Type.
        /// </summary>
        internal static string GetRuntimeMetadata_ScriptType_DisplayName {
            get {
                return ResourceManager.GetString("GetRuntimeMetadata_ScriptType_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information Message Box.
        /// </summary>
        internal static string InformationMessageBoxActivity_DisplayName {
            get {
                return ResourceManager.GetString("InformationMessageBoxActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        internal static string Key_DisplayName {
            get {
                return ResourceManager.GetString("Key_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging.
        /// </summary>
        internal static string Logging_Category {
            get {
                return ResourceManager.GetString("Logging_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message to be displayed in the message box.
        /// </summary>
        internal static string Message_Description {
            get {
                return ResourceManager.GetString("Message_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string Message_DisplayName {
            get {
                return ResourceManager.GetString("Message_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Box Prompt.
        /// </summary>
        internal static string MessageBoxActivity_DisplayName {
            get {
                return ResourceManager.GetString("MessageBoxActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Box.
        /// </summary>
        internal static string Messaging_Category {
            get {
                return ResourceManager.GetString("Messaging_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi Option Message Box.
        /// </summary>
        internal static string MultiOptionMessageBoxActivity_DisplayName {
            get {
                return ResourceManager.GetString("MultiOptionMessageBoxActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list of items that will appear in the prompt window.
        /// </summary>
        internal static string MultiOptionMessageBoxActivity_Items_Description {
            get {
                return ResourceManager.GetString("MultiOptionMessageBoxActivity_Items_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        internal static string MultiOptionMessageBoxActivity_Items_DisplayName {
            get {
                return ResourceManager.GetString("MultiOptionMessageBoxActivity_Items_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The index of the item selected in the list (starting with zero).
        /// </summary>
        internal static string MultiOptionMessageBoxActivity_SelectedIndex_Description {
            get {
                return ResourceManager.GetString("MultiOptionMessageBoxActivity_SelectedIndex_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Index.
        /// </summary>
        internal static string MultiOptionMessageBoxActivity_SelectedIndex_DisplayName {
            get {
                return ResourceManager.GetString("MultiOptionMessageBoxActivity_SelectedIndex_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text of the selected item in the list.
        /// </summary>
        internal static string MultiOptionMessageBoxActivity_SelectedText_Description {
            get {
                return ResourceManager.GetString("MultiOptionMessageBoxActivity_SelectedText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Text.
        /// </summary>
        internal static string MultiOptionMessageBoxActivity_SelectedText_DisplayName {
            get {
                return ResourceManager.GetString("MultiOptionMessageBoxActivity_SelectedText_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets whether the cancel button will be available on the dialog..
        /// </summary>
        internal static string MultiOptionMessageBoxActivity_ShowCancelButton_Description {
            get {
                return ResourceManager.GetString("MultiOptionMessageBoxActivity_ShowCancelButton_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Cancel Button.
        /// </summary>
        internal static string MultiOptionMessageBoxActivity_ShowCancelButton_DisplayName {
            get {
                return ResourceManager.GetString("MultiOptionMessageBoxActivity_ShowCancelButton_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets whether the prompt will use a drop down or individual buttons to represent the different choices..
        /// </summary>
        internal static string MultiOptionMessageBoxActivity_Style_Description {
            get {
                return ResourceManager.GetString("MultiOptionMessageBoxActivity_Style_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style.
        /// </summary>
        internal static string MultiOptionMessageBoxActivity_Style_DisplayName {
            get {
                return ResourceManager.GetString("MultiOptionMessageBoxActivity_Style_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Prompt.
        /// </summary>
        internal static string NotificationWindowActivity_DisplayName {
            get {
                return ResourceManager.GetString("NotificationWindowActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message that will be displayed in the notification window.
        /// </summary>
        internal static string NotificationWindowActivity_Message_Description {
            get {
                return ResourceManager.GetString("NotificationWindowActivity_Message_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string NotificationWindowActivity_Message_DisplayName {
            get {
                return ResourceManager.GetString("NotificationWindowActivity_Message_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The persistence manager to use with the query.  If not provided, a new persistence manager will be created..
        /// </summary>
        internal static string PersistenceManager_Description {
            get {
                return ResourceManager.GetString("PersistenceManager_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistence Manager.
        /// </summary>
        internal static string PersistenceManager_DisplayName {
            get {
                return ResourceManager.GetString("PersistenceManager_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The primary key value of the record to be looked up..
        /// </summary>
        internal static string PrimaryKey_Description {
            get {
                return ResourceManager.GetString("PrimaryKey_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Key.
        /// </summary>
        internal static string PrimaryKey_DisplayName {
            get {
                return ResourceManager.GetString("PrimaryKey_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The query to be executed.  Should take the form “SELECT * FROM #Table# WHERE...” where the table name used corresponds with the BOM object selected..
        /// </summary>
        internal static string Query_Description {
            get {
                return ResourceManager.GetString("Query_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query.
        /// </summary>
        internal static string Query_DisplayName {
            get {
                return ResourceManager.GetString("Query_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resulting BOM objects returned from the query provided..
        /// </summary>
        internal static string QueryResult_Description {
            get {
                return ResourceManager.GetString("QueryResult_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query Result.
        /// </summary>
        internal static string QueryResult_DisplayName {
            get {
                return ResourceManager.GetString("QueryResult_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The query strategy to use.  The default Query Strategy is “Normal”..
        /// </summary>
        internal static string QueryStrategy_Description {
            get {
                return ResourceManager.GetString("QueryStrategy_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query Strategy.
        /// </summary>
        internal static string QueryStrategy_DisplayName {
            get {
                return ResourceManager.GetString("QueryStrategy_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens a window that allows you to see the state of an object.
        /// </summary>
        internal static string QuickWatchActivity_Description {
            get {
                return ResourceManager.GetString("QuickWatchActivity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Watch.
        /// </summary>
        internal static string QuickWatchActivity_DisplayName {
            get {
                return ResourceManager.GetString("QuickWatchActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object to be displayed in the quick watch window..
        /// </summary>
        internal static string QuickWatchActivity_Object_Description {
            get {
                return ResourceManager.GetString("QuickWatchActivity_Object_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object.
        /// </summary>
        internal static string QuickWatchActivity_Object_DisplayName {
            get {
                return ResourceManager.GetString("QuickWatchActivity_Object_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A list of items that will appear in the check list group. For each item a check box will be created. Each check box is unchecked by default. If an item in the items list is Null (e.g. Nothing) the corresponding check box will be disabled.
        /// </summary>
        internal static string RadioGroupWithCheckListBoxActivity_CheckListItems_Description {
            get {
                return ResourceManager.GetString("RadioGroupWithCheckListBoxActivity_CheckListItems_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check List Items.
        /// </summary>
        internal static string RadioGroupWithCheckListBoxActivity_CheckListItems_DisplayName {
            get {
                return ResourceManager.GetString("RadioGroupWithCheckListBoxActivity_CheckListItems_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A list of Boolean indicating if a check box is checked (True) or unchecked (False) when pressing OK. If the CANCEL button is pressed all items default to False. The number of items in this list always matches the number of items supplied as input.
        /// </summary>
        internal static string RadioGroupWithCheckListBoxActivity_CheckListResult_Description {
            get {
                return ResourceManager.GetString("RadioGroupWithCheckListBoxActivity_CheckListResult_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check List Result.
        /// </summary>
        internal static string RadioGroupWithCheckListBoxActivity_CheckListResult_DisplayName {
            get {
                return ResourceManager.GetString("RadioGroupWithCheckListBoxActivity_CheckListResult_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title for the Check list box that will be shown.
        /// </summary>
        internal static string RadioGroupWithCheckListBoxActivity_CheckListTitle_Description {
            get {
                return ResourceManager.GetString("RadioGroupWithCheckListBoxActivity_CheckListTitle_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check List Title.
        /// </summary>
        internal static string RadioGroupWithCheckListBoxActivity_CheckListTitle_DisplayName {
            get {
                return ResourceManager.GetString("RadioGroupWithCheckListBoxActivity_CheckListTitle_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The button (OK, CANCEL) pressed by the user in the dialog. The close button of the dialog (top right X) is handled as a Cancel request.
        /// </summary>
        internal static string RadioGroupWithCheckListBoxActivity_DialogResult_Description {
            get {
                return ResourceManager.GetString("RadioGroupWithCheckListBoxActivity_DialogResult_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog Result.
        /// </summary>
        internal static string RadioGroupWithCheckListBoxActivity_DialogResult_DisplayName {
            get {
                return ResourceManager.GetString("RadioGroupWithCheckListBoxActivity_DialogResult_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio Group With a Check List Box.
        /// </summary>
        internal static string RadioGroupWithCheckListBoxActivity_DisplayName {
            get {
                return ResourceManager.GetString("RadioGroupWithCheckListBoxActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The index of the radio button to be selected by default. First radio button is at index 0. If none supplied, it will default to -1 and no radio button will be pre-selected.
        /// </summary>
        internal static string RadioGroupWithCheckListBoxActivity_RadioGroupIndex_Description {
            get {
                return ResourceManager.GetString("RadioGroupWithCheckListBoxActivity_RadioGroupIndex_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio Group Index.
        /// </summary>
        internal static string RadioGroupWithCheckListBoxActivity_RadioGroupIndex_DisplayName {
            get {
                return ResourceManager.GetString("RadioGroupWithCheckListBoxActivity_RadioGroupIndex_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A list of items that will appear in the radio group. For each item a radio button will be created. If an item in the items list is Null (e.g. Nothing) the corresponding radio button will be disabled.
        /// </summary>
        internal static string RadioGroupWithCheckListBoxActivity_RadioGroupItems_Description {
            get {
                return ResourceManager.GetString("RadioGroupWithCheckListBoxActivity_RadioGroupItems_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio Group Items.
        /// </summary>
        internal static string RadioGroupWithCheckListBoxActivity_RadioGroupItems_DisplayName {
            get {
                return ResourceManager.GetString("RadioGroupWithCheckListBoxActivity_RadioGroupItems_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The index of the radio button that is selected within the radio group when pressing the OK button. If the CANCEL button is pressed, the index always defaults to -1 (i.e no selection). The first radio button has an index of 0.
        /// </summary>
        internal static string RadioGroupWithCheckListBoxActivity_RadioGroupResult_Description {
            get {
                return ResourceManager.GetString("RadioGroupWithCheckListBoxActivity_RadioGroupResult_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio Group Result.
        /// </summary>
        internal static string RadioGroupWithCheckListBoxActivity_RadioGroupResult_DisplayName {
            get {
                return ResourceManager.GetString("RadioGroupWithCheckListBoxActivity_RadioGroupResult_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title for the Radio group box that will be shown.
        /// </summary>
        internal static string RadioGroupWithCheckListBoxActivity_RadioGroupTitle_Description {
            get {
                return ResourceManager.GetString("RadioGroupWithCheckListBoxActivity_RadioGroupTitle_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio Group Title.
        /// </summary>
        internal static string RadioGroupWithCheckListBoxActivity_RadioGroupTitle_DisplayName {
            get {
                return ResourceManager.GetString("RadioGroupWithCheckListBoxActivity_RadioGroupTitle_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime.
        /// </summary>
        internal static string Runtime_Category {
            get {
                return ResourceManager.GetString("Runtime_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Runtime Cache Value.
        /// </summary>
        internal static string SetRuntimeCacheValueActivity_DisplayName {
            get {
                return ResourceManager.GetString("SetRuntimeCacheValueActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to They key of the value to be set in the runtime value cache..
        /// </summary>
        internal static string SetRuntimeCacheValueActivity_Key_Description {
            get {
                return ResourceManager.GetString("SetRuntimeCacheValueActivity_Key_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value to be set in the runtime value cache..
        /// </summary>
        internal static string SetRuntimeCacheValueActivity_Value_Description {
            get {
                return ResourceManager.GetString("SetRuntimeCacheValueActivity_Value_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string Tools_ActivityGroup {
            get {
                return ResourceManager.GetString("Tools_ActivityGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string Value_DisplayName {
            get {
                return ResourceManager.GetString("Value_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning Message Box.
        /// </summary>
        internal static string WarningMessageBoxActivity_DisplayName {
            get {
                return ResourceManager.GetString("WarningMessageBoxActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write To User Log.
        /// </summary>
        internal static string WriteToUserLog_DisplayName {
            get {
                return ResourceManager.GetString("WriteToUserLog_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message to write to the user log.
        /// </summary>
        internal static string WriteToUserLog_LogMessage_Description {
            get {
                return ResourceManager.GetString("WriteToUserLog_LogMessage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Message.
        /// </summary>
        internal static string WriteToUserLog_LogMessage_DisplayName {
            get {
                return ResourceManager.GetString("WriteToUserLog_LogMessage_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes (All) / No (All) / Cancel Message Box.
        /// </summary>
        internal static string YesAllNoAllCancelMessageBoxActivity_DisplayName {
            get {
                return ResourceManager.GetString("YesAllNoAllCancelMessageBoxActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes (All) / No / Cancel Message Box.
        /// </summary>
        internal static string YesAllNoCancelMessageBoxActivity_DisplayName {
            get {
                return ResourceManager.GetString("YesAllNoCancelMessageBoxActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes / No / Cancel Message Box.
        /// </summary>
        internal static string YesNoCancelMessageBoxActivity_DisplayName {
            get {
                return ResourceManager.GetString("YesNoCancelMessageBoxActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes / No Message Box.
        /// </summary>
        internal static string YesNoMessageBoxActivity_DisplayName {
            get {
                return ResourceManager.GetString("YesNoMessageBoxActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes/No Prompt.
        /// </summary>
        internal static string YesNoPromptActivity_DisplayName {
            get {
                return ResourceManager.GetString("YesNoPromptActivity_DisplayName", resourceCulture);
            }
        }
    }
}
